---
collections:
  # Core modules for system, service, and package management
  - name: community.general
    version: ">=6.0.0"

  # POSIX-compliant modules (users, groups, permissions, mounts)
  - name: ansible.posix
    version: ">=1.5.0"

  # Utility plugins (filters, lookups, tests)
  - name: ansible.utils
    version: ">=2.9.0"

  # Cryptographic tools (certs, keys, TLS)
  - name: community.crypto
    version: ">=2.6.0"

  # Networking modules (interfaces, firewall, routing)
  - name: community.network
    version: ">=5.0.0"
