---
# Baseline wrapper

- name: Include account_identity controls
  import_tasks: "{{ role_path }}/account_identity/tasks/main.yml"


- name: Include access_control controls
  import_tasks: "{{ role_path }}/access_control/tasks/main.yml"
