---
- name: Restrict su to sudo group via pam_wheel
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^#?auth\s+required\s+pam_wheel.so use_uid group=sudo'
    line: 'auth required pam_wheel.so use_uid group=sudo'
    backup: yes
