---

- name: Restrict su to sudo group via pam_wheel
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^#?auth\s+required\s+pam_wheel.so use_uid group=sudo'
    line: 'auth required pam_wheel.so use_uid group=sudo'
    backup: yes

- name: "SU | ensure wheel exists"
  group: { name: wheel, state: present }

- name: "SU | enforce pam_wheel"
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^\s*auth\s+required\s+pam_wheel\.so'
    line: 'auth required pam_wheel.so use_uid group=wheel'

- name: "SU | wheel must be empty"
  shell: |
    getent group wheel | awk -F: '{print $4}' | tr ',' '
' | grep -vE '^$|^root$' || true
  register: current_wheel
  changed_when: false

- name: "SU | remove wheel non-root members"
  when: current_wheel.stdout_lines|length>0
  user:
    name: "{{ item }}"
    groups: ""
    append: no
  loop: "{{ current_wheel.stdout_lines }}"
