---

- name: Ensure PAM modules present
  apt:
    name: [libpam-modules, libpam-pwquality]
    state: present

- name: Ensure faillock.conf present
  ansible.builtin.template:
    src: "{{ role_path }}/authz/templates/faillock.conf.j2"
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: '0644'
  when: enable_pam_faillock | default(true)

- name: Ensure pam_faillock is in common-auth (preauth and authfail)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-auth
    insertafter: BOF
    line: "{{ item }}"
  loop:
    - 'auth required pam_faillock.so preauth'
    - 'auth [default=die] pam_faillock.so authfail'
  when: enable_pam_faillock | default(true)

#- name: Ensure pam_faillock is in common-account
#  ansible.builtin.lineinfile:
#    path: /etc/pam.d/common-account
#    insertafter: BOF
#    line: 'account required pam_faillock.so'
#  when: enable_pam_faillock | default(true)

- name: Enforce delay after failed logon attempts (pam_faildelay)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-auth
    line: 'auth required pam_faildelay.so delay={{ pam_faildelay_us | default(4000000) }}'
    insertafter: BOF
  when: enable_pam_faildelay | default(true)

- name: Ensure PAM displays last login/failed attempts (pam_lastlog)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    regexp: '^session\\s+required\\s+pam_lastlog\\.so'
    line: 'session required pam_lastlog.so showfailed'
    create: yes
  when: enable_pam_lastlog | default(true)

- name: Enforce login lockouts (common-auth)
  lineinfile:
    path: /etc/pam.d/common-auth
    insertafter: BOF
    line: 'auth required pam_faillock.so preauth silent audit deny=5 unlock_time=900'
    create: yes
    backup: yes

- name: Enforce account lockouts (common-account)
  lineinfile:
    path: /etc/pam.d/common-account
    insertafter: BOF
    line: 'account required pam_faillock.so'
    create: yes
    backup: yes
