- name: Install NGINX
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy NGINX reverse proxy config from template
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Ensure ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present
  tags: [network_security]

- name: Allow NGINX before enabling UFW
  community.general.ufw:
    rule: allow
    port: "{{ ufw_nginx_port }}"
    proto: tcp
  when: ufw_enable and ufw_allow_nginx
  tags: [network_security]
  
- name: Test NGINX configuration
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Show NGINX config test output
  debug:
    var: nginx_test.stdout_lines
