stig_enabled_tags:
  - auditd
  - ssh
  - pam
  - banner
  - cron
  - fips
  - ctrl_alt_del
  - file_permissions

ubuntu24stig_disruption_high: false
ubtu24stig_run_audit: true
ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"

cloudflare_api_token: "YOUR_API_TOKEN"
cloudflare_zone: "timmos.com.au"
cloudflare_account_id: "YOUR_ACCOUNT_ID"
cloudflare_tunnel_name: "homelab-tunnel"
cloudflare_tunnel_id: "YOUR_TUNNEL_ID"
cloudflare_tunnel_secret: "YOUR_TUNNEL_SECRET"
cloudflared_bin_path: "/usr/local/bin/cloudflared"

