stig_enabled_tags:
  - auditd
  - ssh
  - pam
  - banner
  - cron
  - fips
  - ctrl_alt_del
  - file_permissions

ubuntu24stig_disruption_high: false
ubtu24stig_run_audit: true


# ---- CIFS Mount Points ----
username: "{{ lookup('env', 'CIFS_USERNAME') }}"
password: "{{ lookup('env', 'CIFS_PASSWORD') }}"

# ---- Time Sync ----
chrony_servers:
  - "time.cloudflare.com iburst nts maxsamples 5"
  - "au.pool.ntp.org iburst"
remove_timesyncd: true

# ---- Network Security / UFW ----
ufw_enable: true
ufw_default_incoming: "deny"
ufw_default_outgoing: "allow"
ufw_allow_ssh: true
ufw_ssh_port: 22
ufw_allow_nginx: true
ufw_nginx_port: 80
remove_insecure_network_pkgs: [telnetd, rsh-server]

# ---- SSH Hardening ----
sshd_pkg: openssh-server
sshd_x11_forwarding: "no"
sshd_x11_use_localhost: "yes"
sshd_permit_empty_passwords: "no"
sshd_permit_user_env: "no"
sshd_ciphers:
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes128-ctr
sshd_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256
sshd_kex:
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group-exchange-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group14-sha256

# ---- File Integrity & Audit ----
install_aide: true
auditd_rules_immutable: true
audit_rules_extra: []

# ---- Auth & Access ----
lock_root_account: true          # [true] The root account is locked, preventing direct login. This enhances security by forcing use of sudo.
pass_min_days: 1                 # [1] Users must wait at least 1 day before changing their password again. Prevents rapid cycling of passwords.
pass_max_days: 60                # [60] Passwords expire after 60 days. 
minlen: 15                       # [15] Minimum total password length is 15 characters.
difok: 8                         # [8] Password must differ from the old password by at least 8 characters.
ucredit: -1                      # [-1] Requires at least 1 uppercase letter in the password.
lcredit: -1                      # [-1] Requires at least 1 lowercase letter.
dcredit: -1                      # [-1] Requires at least 1 digit.
ocredit: -1                      # [-1] Requires at least 1 special character (e.g., @, #, $).
enforcing_pwquality: 0           # [1] Password quality enforcement is disabled. This means the above complexity rules may not be enforced.
dictcheck: 1                     # [1] Dictionary check is enabled. Prevents use of common dictionary words in passwords.
pam_fail_delay_microseconds: 4000000
pam_faillock:
  deny: 3
  fail_interval: 900
  unlock_time: 0
enable_sssd_mfa: false

# ---- Crypto / FIPS ----
enable_fips: false      # Not compatible with my hardware. (Causes panic during boot.)
enable_usg: true
ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"

# ---- Logging & Journal ----
secure_log_files: true

# ---- System Hardening ----
sysctl_settings:
  kernel.dmesg_restrict: 1
  net.ipv4.tcp_syncookies: 1
  kernel.randomize_va_space: 2

# ---- Session Timeouts ----
ssh_idle_timeout_seconds: 600
ssh_alive_count_max: 1
max_concurrent_sessions: 10

# ---- Patching / APT ----
remove_unused_dependencies: true
remove_unused_kernels: true
disallow_unauthenticated_apt: true
