stig_enabled_tags:
  - auditd
  - ssh
  - pam
  - banner
  - cron
  - fips
  - ctrl_alt_del
  - file_permissions

ubuntu24stig_disruption_high: false
ubtu24stig_run_audit: true
ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"

cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
cloudflare_zone: "{{ lookup('env', 'CLOUDFLARE_ZONE') }}"
cloudflare_account_id: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_ID') }}"
cloudflare_tunnel_name: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_NAME') }}"
cloudflare_tunnel_id: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_ID') }}"
cloudflare_tunnel_secret: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_SECRET') }}"
cloudflared_bin_path: "/usr/local/bin/cloudflared"
cloudflare_global_api_token: "{{ lookup('env', 'CLOUDFLARE_GLOBAL_API_TOKEN') }}"
cloudflare_global_api_email: "internet@timmos.com.au"
cloudflare_apps_api_token: "{{ lookup('env', 'CLOUDFLARE_APPS_TOKEN') }}"
access_otp_phone:  "{{ lookup('env', 'ACCESS_OTP_PHONE') }}"
ansible_user: "tim"
tunnel_name: "dmz-tunnel"
verified_email_domains:
  - timmos.com.au
  
cloudflare_access_apps:
  - name: "Sonarr"
    domain: "sonarr.timmos.com.au"
    hostname: "sonarr.timmos.com.au"
    local_service: "http://192.168.1.100:8989"
    email: "sonarr@timmos.com.au"

  - name: "Radarr"
    domain: "radarr.timmos.com.au"
    hostname: "radarr.timmos.com.au"
    local_service: "http://192.168.1.100:7878"
    email: "radarr@timmos.com.au"

  - name: "Lidarr"
    domain: "lidarr.timmos.com.au"
    hostname: "lidarr.timmos.com.au"
    local_service: "http://192.168.1.100:8686"
    email: "lidarr@timmos.com.au"

  - name: "Prowlarr"
    domain: "prowlarr.timmos.com.au"
    hostname: "prowlarr.timmos.com.au"
    local_service: "http://192.168.1.100:9696"
    email: "prowlarr@timmos.com.au"

  - name: "VueTorrent"
    domain: "vuetorrent.timmos.com.au"
    hostname: "vuetorrent.timmos.com.au"
    local_service: "http://192.168.1.100:8080"
    email: "vuetorrent@timmos.com.au"

  - name: "Readarr"
    domain: "readarr.timmos.com.au"
    hostname: "readarr.timmos.com.au"
    local_service: "http://192.168.1.100:8787"
    email: "readarr@timmos.com.au"

nginx_upstreams:
  - public_hostname: sonarr.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 8989
  - public_hostname: radarr.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 7878
  - public_hostname: lidarr.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 8686
  - public_hostname: prowlarr.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 9696
  - public_hostname: vuetorrent.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 8080
  - public_hostname: readarr.timmos.com.au
    internal_ip: 192.168.1.100
    internal_port: 8787
