stig_enabled_tags:
  - auditd
  - ssh
  - pam
  - banner
  - cron
  - fips
  - ctrl_alt_del
  - file_permissions

ubuntu24stig_disruption_high: false
ubtu24stig_run_audit: true
ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"

cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
cloudflare_zone: "{{ lookup('env', 'CLOUDFLARE_ZONE') }}"
cloudflare_account_id: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_ID') }}"
cloudflare_tunnel_name: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_NAME') }}"
cloudflare_tunnel_id: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_ID') }}"
cloudflare_tunnel_secret: "{{ lookup('env', 'CLOUDFLARE_TUNNEL_SECRET') }}"
cloudflared_bin_path: "/usr/local/bin/cloudflared"
cloudflare_global_api_token: "{{ lookup('env', 'CLOUDFLARE_GLOBAL_API_TOKEN') }}"
cloudflare_apps_api_token: "{{ lookup('env', 'CLOUDFLARE_APPS_TOKEN') }}"
ansible_user: "tim"
tunnel_name: "dmz-tunnel"

cloudflare_access_apps:
  - name: "Sonarr"
    domain: "sonarr.timmos.com.au"
    hostname: "sonarr.timmos.com.au"
    local_service: "http://192.168.1.100:8989"
    email: "sonarr@timmos.com.au"
    sonarr_ip: 192.168.1.100
    sonarr_port: 8989

  - name: "Radarr"
    domain: "radarr.timmos.com.au"
    hostname: "radarr.timmos.com.au"
    local_service: "http://192.168.1.100:7878"
    email: "radarr@timmos.com.au"
    radarr_ip: 192.168.1.100
    radarr_port: 7878
