---
- name: Conditionally attach to Ubuntu Pro and enable USG
  hosts: all
  become: true
  vars:
    ubuntu_pro_token: "{{ ubuntu_pro_token }}"  # Passed via SemaphoreUI CLI args

  tasks:

    - name: Ensure 'pro' CLI is installed
      apt:
        name: ubuntu-advantage-tools
        state: present
        update_cache: yes

    - name: Check current Ubuntu Pro status
      command: pro status --format json
      register: pro_status_raw
      changed_when: false

    - name: Parse Ubuntu Pro status
      set_fact:
        pro_status: "{{ pro_status_raw.stdout | from_json }}"

    - name: Skip if already attached
      debug:
        msg: "System already attached to Ubuntu Pro. Skipping attach."
      when: pro_status.account.contract_token is defined

    - name: Attach to Ubuntu Pro (if not already attached)
      command: >
        pro attach {{ ubuntu_pro_token }}
      when: pro_status.account.contract_token is not defined
      register: pro_attach_result
      changed_when: "'already attached' not in pro_attach_result.stdout"

    - name: Skip if USG already enabled
      debug:
        msg: "USG already enabled. Skipping."
      when: "'usg' in pro_status.enabled_services"

    - name: Enable USG (Ubuntu Security Guide)
      command: pro enable usg
      when: "'usg' not in pro_status.enabled_services"
      register: usg_enable
      changed_when: "'enabled' in usg_enable.stdout"

    - name: Show final Ubuntu Pro status
      command: pro status
      register: final_status
      changed_when: false

    - name: Display final status
      debug:
        var: final_status.stdout
