---
- name: Attach to Ubuntu Pro using config file and enable FIPS + USG
  hosts: all
  become: true
  vars:
    ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"

  tasks:

    - name: Ensure 'pro' CLI is installed
      apt:
        name: ubuntu-advantage-tools
        state: present
        update_cache: yes

    - name: Validate Ubuntu Pro token
      fail:
        msg: "UBUNTU_PRO_TOKEN is not set or invalid."
      when: ubuntu_pro_token is undefined or ubuntu_pro_token | length < 10

    - name: Create Ubuntu Pro attach config file
      copy:
        content: |
          token: "{{ ubuntu_pro_token }}"
          enable_services:
            - fips
            - usg
        dest: /tmp/pro-attach-config.yaml
        mode: '0600'

    - name: Attach to Ubuntu Pro using config file
      command: pro attach --attach-config /tmp/pro-attach-config.yaml
      register: pro_attach_result
      changed_when: "'already attached' not in pro_attach_result.stdout"

    - name: Display enabled services
      command: pro status
      register: pro_status
      changed_when: false

    - name: Show Ubuntu Pro status
      debug:
        var: pro_status.stdout

    - name: Reboot if FIPS was just enabled
      reboot:
        msg: "Rebooting to apply FIPS kernel modules"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: "'fips' in pro_status.stdout"

    - name: Verify FIPS mode is active
      command: fips-mode-setup --check
      register: fips_check
      changed_when: false

    - name: Show FIPS verification result
      debug:
        var: fips_check.stdout
