---
roles:
  # Ubuntu Pro attachment and USG enablement
  - name: ubuntu_pro_attach
    src: ./roles/ubuntu_pro_attach

  # Cloudflare tunnel setup
  - name: cloudflared
    src: git+https://github.com/example-org/ansible-role-cloudflared.git
    version: main

  # General security hardening
  - name: geerlingguy.security
    version: 2.0.0

collections:
  # Community modules (e.g. system, networking, cloud)
  - name: community.general
    version: ">=6.0.0"

  # POSIX modules (e.g. for user, group, file permissions)
  - name: ansible.posix
    version: ">=1.5.0"

  # System-level utilities
  - name: ansible.utils
    version: ">=2.9.0"
