---
- name: Render STIG sysctl config
  ansible.builtin.template:
    src: 99-stig-sysctl.conf.j2
    dest: /etc/sysctl.d/99-stig-sysctl.conf
    owner: root
    group: root
    mode: "0644"
  notify: Apply sysctl
  tags: [hardening]

- name: Check if kdump-tools is installed
  ansible.builtin.shell: dpkg -l | grep -qw kdump-tools
  register: kdump_installed
  changed_when: false
  failed_when: false

- name: Disable kdump-tools service if installed
  ansible.builtin.service:
    name: kdump-tools
    enabled: no
    state: stopped
  when: kdump_installed.rc == 0
  tags: [hardening]

