---
- name: Install Ubuntu Security Guide (USG)
  apt:
    name: ubuntu-security-guide
    state: present
    update_cache: yes

- name: Optionally apply DISA-STIG baseline
  command: usg fix disa_stig
  when: usg_apply_fix | default(false)

- name: Audit DISA-STIG rules with USG
  command: usg audit disa_stig
  register: usg_audit
  changed_when: false

- name: Save USG audit report
  copy:
    dest: /var/tmp/usg_audit.txt
    content: "{{ usg_audit.stdout }}"
