---
- name: Install OpenSCAP + SCAP Security Guide
  apt:
    name: [openscap-scanner, scap-security-guide]
    state: present
    update_cache: yes

- name: Detect Ubuntu SCAP datastream
  shell: ls -1 /usr/share/xml/scap/ssg/content/ssg-ubuntu*-ds.xml | head -n1
  args:
    warn: false
  register: ssg_ds
  changed_when: false
  failed_when: ssg_ds.stdout | length == 0

- name: Evaluate STIG profile
  command: oscap xccdf eval --profile stig --results /var/tmp/openscap-results.xml {{ ssg_ds.stdout }}
  register: oscap
  changed_when: false
  ignore_errors: yes

- name: Save OpenSCAP summary
  copy:
    dest: /var/tmp/openscap-summary.txt
    content: "{{ oscap.stdout }}"
