
---
- name: Ensure Universe repo is enabled (USG deps sometimes live here)
  become: true
  ansible.builtin.command: add-apt-repository -y universe
  register: add_universe
  changed_when: add_universe.rc == 0 and ('universe' in (add_universe.stdout | lower))
  failed_when: false
  when: enable_usg | default(true)
  tags: ['usg']

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: enable_usg | default(true)
  tags: ['usg']

- name: Ensure Ubuntu Pro client is present
  become: true
  ansible.builtin.apt:
    name: ubuntu-advantage-tools
    state: present
    update_cache: yes
  when: enable_usg | default(true)
  tags: ['usg']

- name: Attach to Ubuntu Pro if token provided (non-interactive)
  become: true
  ansible.builtin.command: pro attach {{ pro_token }}
  when:
    - enable_usg | default(true)
    - pro_token is defined
    - pro_token | length > 0
  register: pro_attach
  changed_when: pro_attach.rc == 0
  failed_when: pro_attach.rc not in [0, 2]
  tags: ['usg']

- name: Enable the USG channel via Pro
  become: true
  ansible.builtin.command: pro enable usg
  register: pro_enable_usg
  changed_when: "'enabled' in (pro_enable_usg.stdout | lower)"
  failed_when: false
  when: enable_usg | default(true)
  tags: ['usg']

- name: Flag USG availability for this release
  ansible.builtin.set_fact:
    usg_available: "{{ 'not available' not in (pro_enable_usg.stdout | lower) }}"
  when: enable_usg | default(true)
  tags: ['usg']

- name: Install USG CLI (package is 'usg')
  become: true
  ansible.builtin.apt:
    name: usg
    state: present
    update_cache: yes
  when:
    - enable_usg | default(true)
    - usg_available | default(true)
  tags: ['usg']

- name: Explain skip when USG is not available
  ansible.builtin.debug:
    msg: "USG not available on this 24.04 build (per Pro). Skipping USG steps."
  when:
    - enable_usg | default(true)
    - not usg_available | default(true)
  tags: ['usg']

- name: Note FIPS Updates recommended for DISA-STIG (reboot required)
  ansible.builtin.debug:
    msg: "DISA-STIG selected: Canonical recommends enabling 'fips-updates'. This typically requires a reboot."
  when:
    - enable_usg | default(true)
    - usg_available | default(true)
    - (usg_profile | default('disa_stig')) == 'disa_stig'
  tags: ['usg']

- name: USG | audit {{ usg_profile | default('disa_stig') }}
  become: true
  ansible.builtin.command: "usg audit {{ usg_profile | default('disa_stig') }}"
  register: usg_audit
  changed_when: false
  failed_when: false
  when:
    - enable_usg | default(true)
    - usg_available | default(true)
    - usg_run_audit | default(true)
  tags: ['usg']

- name: Save USG audit report
  become: true
  ansible.builtin.copy:
    dest: "{{ usg_reports_dir | default('/var/tmp') }}/usg-audit-{{ usg_profile | default('disa_stig') }}.txt"
    content: "{{ usg_audit.stdout | default('') }}"
    mode: '0644'
  when:
    - enable_usg | default(true)
    - usg_available | default(true)
    - usg_run_audit | default(true)
  tags: ['usg']

- name: USG | fix {{ usg_profile | default('disa_stig') }} (DISRUPTIVE)
  become: true
  ansible.builtin.command: "usg fix {{ usg_profile | default('disa_stig') }}"
  register: usg_fix
  changed_when: true
  when:
    - enable_usg | default(true)
    - usg_available | default(true)
    - usg_apply_fix | default(false)
  tags: ['usg']
