- name: Update and upgrade APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  tags: [update]

- name: Install essential packages for Ubuntu 24.04 minimal server
  ansible.builtin.apt:
    name:
      #- build-essential
      - curl
      #- wget
      - net-tools
      #- iproute2
      #- gnupg
      - ca-certificates
      - software-properties-common
      - unzip
      - zip
      - htop
      - nano
      - git
      - rsyslog
      #- lsof
      - bash-completion
      - openssh-server
      - htop
    state: present
    update_cache: yes
  tags: [essential]

- name: Remove unwanted packages from Ubuntu 24.04 Server
  ansible.builtin.apt:
    name:
      - snapd
      - ufw
      - apport
      - landscape-common
      - popularity-contest
      - friendly-recovery
      - ubuntu-release-upgrader-core
      - update-manager-core
    state: absent
    purge: yes
  tags: [cleanup]

- name: Remove unwanted services from Ubuntu 24.04 Server
  ansible.builtin.apt:
    name:
      - snapd
      #- ufw           # If using another firewall like iptables/nftables
      - apport        # Error reporting
      - landscape-common
      - update-manager-core
      - friendly-recovery
      - whoopsie      # Crash reporting
      - modemmanager  # Not needed on servers
      - avahi-daemon  # Zeroconf, not needed on most servers
      - cups          # Printing service
    state: absent
    purge: yes
  tags: [cleanup]

