
- name: Update and upgrade APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes
    dpkg_options: 'force-confdef,force-confold'
  tags: [update]


- name: Install essential packages for Ubuntu 24.04 minimal server
  ansible.builtin.apt:
    name:
      #- curl
      #- net-tools
      #- ca-certificates
      #- software-properties-common
      #- unzip
      #- zip
      - htop
      - nano
      #- git
      - rsyslog
      - bash-completion
      #- openssh-server
    state: present
    update_cache: yes
  tags: [essential]

- name: Remove unwanted packages from Ubuntu 24.04 Server
  ansible.builtin.apt:
    name:
      - snapd
      - ufw
      - apport
      - landscape-common
      - popularity-contest
      - friendly-recovery
      - ubuntu-release-upgrader-core
      - update-manager-core
    state: absent
    purge: yes
  tags: [cleanup]

- name: Remove unwanted services from Ubuntu 24.04 Server
  ansible.builtin.apt:
    name:
      - snapd
      #- ufw           # If using another firewall like iptables/nftables
      - apport        # Error reporting
      - landscape-common
      - update-manager-core
      - friendly-recovery
      - whoopsie      # Crash reporting
      - modemmanager  # Not needed on servers
      - avahi-daemon  # Zeroconf, not needed on most servers
      - cups          # Printing service
    state: absent
    purge: yes
  tags: [cleanup]

