---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Install AppArmor packages
  apt:
    name: [apparmor, apparmor-utils]
    state: present
    update_cache: yes

- name: Ensure AppArmor running
  systemd:
    name: apparmor
    enabled: yes
    state: started

- name: Verify AppArmor status (report only)
  command: aa-status
  register: aa
  changed_when: false
  failed_when: false
