---

- name: Blacklist uncommon filesystem kernel modules
  copy:
    dest: /etc/modprobe.d/blacklist-stig.conf
    content: |
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install squashfs /bin/true
      install udf /bin/true
      install vfat /bin/true
      install usb-storage /bin/true
      install overlay /bin/true
    owner: root
    group: root
    mode: '0644'
