---
        # -------------------------------------------------------------------
        # Ubuntu 24.04 LTS — DISA-STIG | system_config | disable_unnecessary_services.yml
        # Guarded by variable: enable_disable_unnecessary_services
        # -------------------------------------------------------------------

- name: Disable legacy and insecure network services (best effort)
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - telnet
    - rsh
    - rexec
    - vsftpd
  ignore_errors: yes
