---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Disable legacy network services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - telnet
    - rsh
    - rexec
    - vsftpd
  ignore_errors: yes
