---
# system_config control group — included by baseline/tasks/main.yml

- name: Run disable unnecessary services
  import_tasks: "{{ role_path }}/system_config/tasks/disable_unnecessary_services.yml"
  when: enable_disable_unnecessary_services

- name: Run secure boot settings
  import_tasks: "{{ role_path }}/system_config/tasks/secure_boot_settings.yml"
  when: enable_secure_boot_settings

- name: Run kernel hardening sysctl
  import_tasks: "{{ role_path }}/system_config/tasks/kernel_hardening_sysctl.yml"
  when: enable_kernel_hardening_sysctl

- name: Run motd banners
  import_tasks: "{{ role_path }}/system_config/tasks/motd_banners.yml"
  when: enable_motd_banners

- name: Run Gnome lockdown
  import_tasks: "{{ role_path }}/system_config/tasks/gnome_lockdown.yml"
  when: gnome_lockdown

- name: Run time sync
  import_tasks: "{{ role_path }}/system_config/tasks/time_sync.yml"
  when: enable_time_sync

- name: Run blacklist unused filesystems
  import_tasks: "{{ role_path }}/system_config/tasks/blacklist_unused_filesystems.yml"
  when: enable_blacklist_unused_filesystems

- name: Run apparmor enable
  import_tasks: "{{ role_path }}/system_config/tasks/apparmor_enable.yml"
  when: enable_apparmor_enable

- name: Run vendor supported release
  import_tasks: "{{ role_path }}/system_config/tasks/vendor_supported_release.yml"
  when: enable_vendor_supported_release

- name: Attach to Ubuntu Pro and enable services
  import_tasks: "{{ role_path }}/system_config/tasks/ubuntu_pro.yml"
  when: enable_ubuntu_pro | default(true)



- import_tasks: "{{ role_path }}/system_config/tasks/apport_disable.yml"
  when: enable_apport_disable

- import_tasks: "{{ role_path }}/system_config/tasks/umask_and_timeout.yml"
  when: enable_umask_and_timeout

- import_tasks: "{{ role_path }}/system_config/tasks/core_dumps_disable.yml"
  when: enable_core_dumps_disable

