---

- name: Deploy hardened GRUB defaults
  template:
    src: "{{ role_path }}/system_config/templates/grub.j2"
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'

- name: Configure bootloader superuser/password if provided
  blockinfile:
    path: /etc/grub.d/40_custom
    create: yes
    block: |
      set superusers="root"
      password_pbkdf2 root {{ bootloader_password_pbkdf2 }}
  when: bootloader_password_pbkdf2 | length > 0

- name: "GRUB | ensure apparmor boot flags"
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor"'

- name: Apply GRUB changes
  command: update-grub
