
---
- name: Ensure Pro client present
  become: true
  ansible.builtin.apt:
    name: ubuntu-advantage-tools
    state: present
    update_cache: yes
  tags: ['ubuntu_pro']

- name: Check current Pro status (JSON)
  ansible.builtin.command: pro status --format json
  register: pro_status
  changed_when: false
  failed_when: false
  tags: ['ubuntu_pro']

- name: Attach this machine to Ubuntu Pro (non-interactive) if a token is provided
  when:
    - pro_token is defined
    - pro_token | length > 0
  become: true
  ansible.builtin.command: pro attach {{ pro_token }}
  register: pro_attach
  failed_when: pro_attach.rc not in [0, 2]
  changed_when: pro_attach.rc == 0
  tags: ['ubuntu_pro']

- name: Refresh Pro status after attach
  ansible.builtin.command: pro status --format json
  register: pro_status_after
  changed_when: false
  failed_when: false
  tags: ['ubuntu_pro']

- name: Build list of services to enable (defaults + toggles)
  ansible.builtin.set_fact:
    pro_services_effective: >-
      {{
        (pro_services_to_enable | default(['esm-infra','esm-apps']))
        + (['livepatch'] if (pro_enable_livepatch | default(false)) else [])
        + (['fips-updates'] if (pro_enable_fips_updates | default(false)) else [])
        + (['usg'] if (enable_usg | default(false)) else [])
      }}
  tags: ['ubuntu_pro']

- name: Enable requested Ubuntu Pro services (idempotent)
  become: true
  ansible.builtin.command: "pro enable {{ item }} --assume-yes"
  register: pro_enable_results
  loop: "{{ pro_services_effective | unique }}"
  changed_when: "'enabled' in (pro_enable_results.stdout | default('') | lower) or ('results' in pro_enable_results and 'enabled' in (pro_enable_results.results[0].stdout | default('') | lower))"
  failed_when: false
  tags: ['ubuntu_pro']

- name: Note that a reboot is required when enabling FIPS Updates
  ansible.builtin.debug:
    msg: "FIPS Updates were requested; a reboot is typically required to complete installation."
  when: "'fips-updates' in pro_services_effective"
  tags: ['ubuntu_pro']

- name: Update package lists after enabling ESM
  become: true
  ansible.builtin.apt:
    update_cache: yes
  tags: ['ubuntu_pro']
