---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Force SSH Protocol 2 only
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol'
    line: 'Protocol 2'
    create: yes
  notify: restart_sshd
