- name: Install Ubuntu Pro client (required for FIPS repositories)
  apt:
    name: ubuntu-advantage-tools
    state: present
    update_cache: yes
  when: pro_token is defined and pro_token != ''
  tags: ['fips']

# --- Check attachment status ---
- name: Check Ubuntu Pro status
  command: pro status --format json
  register: pro_status
  changed_when: false
  failed_when: false
  when:
    - pro_token is defined and pro_token != ''
  tags: ['fips']

- name: Parse Ubuntu Pro status
  set_fact:
    pro_attached_status: "{{ pro_status.stdout | from_json | json_query('status') }}"
  when:
    - pro_status.stdout is defined
  tags: ['fips']

- name: Attach to Ubuntu Pro if not already attached
  become: true
  ansible.builtin.command: pro attach {{ pro_token }}
  when:
    - pro_token is defined
    - pro_token | length > 0
    - pro_attached_status == 'not-attached'
  register: pro_attach
  changed_when: "'This machine is now attached' in pro_attach.stdout"
  failed_when: pro_attach.rc != 0
  tags: ['fips']

# --- Check FIPS status ---
- name: Check if FIPS updates are already enabled
  command: pro status --format json
  register: pro_status_fips
  changed_when: false
  failed_when: false
  when: pro_token is defined and pro_token != ''
  tags: ['fips']

- name: Set fact for FIPS updates status
  set_fact:
    fips_enabled: >-
      {{
        (pro_status_fips.stdout | from_json).services['fips-updates'].status is defined and
        (pro_status_fips.stdout | from_json).services['fips-updates'].status == 'enabled'
      }}
  when: pro_status_fips.stdout is defined
  tags: ['fips']

# --- Enable FIPS ---
- name: Enable FIPS updates channel (idempotent)
  command: pro enable fips-updates --assume-yes
  register: fips_enable
  changed_when: fips_enable.stdout is defined and 'enabled' in fips_enable.stdout | lower
  failed_when: >
    fips_enable.rc != 0 and
    ('already enabled' not in fips_enable.stdout | lower)
  when:
    - pro_token is defined and pro_token != ''
    - pro_attached | default(false)
    - not fips_enabled | default(false)
  notify: Reboot if FIPS enabled
  tags: ['fips']

# --- GRUB config ---
- name: Ensure FIPS is enabled on next boot
  copy:
    dest: /etc/default/grub.d/99-fips.cfg
    content: |
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX fips=1"
    owner: root
    group: root
    mode: '0644'

- name: Update grub
  command: update-grub

#- name: Reboot for FIPS
#  ansible.builtin.reboot:
#  when: enable_fips_mode | default(false)