---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Install Ubuntu Pro client (required for FIPS)
  apt:
    name: ubuntu-advantage-tools
    state: present
  when: pro_token is defined and pro_token != ''

- name: Attach Ubuntu Pro subscription
  command: pro attach {{ pro_token }}
  when: pro_token is defined and pro_token != ''
  register: pro_attach
  changed_when: "'Attached' in pro_attach.stdout or 'already attached' in pro_attach.stdout | lower"

- name: Enable FIPS updates
  command: pro enable fips-updates
  when: pro_token is defined and pro_token != ''

- name: Ensure FIPS is enabled on next boot (adds fips=1)
  copy:
    dest: /etc/default/grub.d/99-fips.cfg
    content: |
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX fips=1"
  notify: []

- name: Update grub
  command: update-grub
