- name: Install Ubuntu Pro client (required for FIPS repositories)
  apt:
    name: ubuntu-advantage-tools
    state: present
  when: pro_token is defined and pro_token != ''

- name: Check if system is already attached to Ubuntu Pro
  command: pro status --format json
  register: pro_status
  changed_when: false
  failed_when: false
  when: pro_token is defined and pro_token != ''

- name: Set fact for Ubuntu Pro attachment status
  set_fact:
    pro_attached_status: "{{ pro_status.stdout | from_json | json_query('status') }}"
  when: pro_status.stdout is defined

- name: Attach Ubuntu Pro subscription
  command: pro attach {{ pro_token }}
  when:
    - pro_token is defined and pro_token != ''
    - pro_attached_status == 'not-attached'
  register: pro_attach
  changed_when: "'attached' in pro_attach.stdout | lower"
  failed_when: pro_attach.rc != 0

- name: Enable FIPS updates channel
  command: pro enable fips-updates
  when: pro_token is defined and pro_token != ''

- name: Ensure FIPS is enabled on next boot
  copy:
    dest: /etc/default/grub.d/99-fips.cfg
    content: |
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX fips=1"
    owner: root
    group: root
    mode: '0644'

- name: Update grub
  command: update-grub
