- name: Create Cloudflare Access app for Sonarr
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Sonarr"
      domain: "sonarr.timmos.com.au"
      type: "self_hosted"
      session_duration: "24h"
      policies:
        - decision: allow
          include:
            - email:
                email: "your@email.com"
    status_code: 200

- name: Create Cloudflare Access app for Radarr
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Radarr"
      domain: "radarr.timmos.com.au"
      type: "self_hosted"
      session_duration: "24h"
      policies:
        - decision: allow
          include:
            - email:
                email: "your@email.com"
    status_code: 200
