# Headless token mode defaults
cloudflare_api_token: "{{ cloudflare_api_token }}"
cloudflare_account_id: "{{ cloudflare_account_id }}"
cloudflare_zone: "{{ cloudflare_zone }}"
cloudflared_bin_path: /usr/local/bin/cloudflared
cloudflared_config_path: /etc/cloudflared/config.yml
cloudflared_tunnel_id: ""                # From Terraform output
cloudflared_tunnel_credentials_json: ""  # From Terraform output (JSON string)
cloudflared_service_name: cloudflared
tunnel_name: "home-edge"

# Path to Terraform working directory containing .tfstate
terraform_dir: /opt/terraform/cloudflared

# Hostname/service mapping for ingress
cloudflared_ingress:
  - hostname: proxy.timmos.com.au
    service: http://localhost:80
  - service: http_status:404
  
cloudflare_access_apps:
  - name: "Sonarr"
    domain: "sonarr.timmos.com.au"
    local_service: "http://192.168.1.100:8989"
    email: "sonarr@timmos.com.au"
  - name: "Radarr"
    domain: "radarr.timmos.com.au"
    local_service: "http://192.168.1.100:7878"
    email: "radarr@timmos.com.au"
