# Headless token mode defaults
cloudflare_api_token: "{{ cloudflare_api_token }}"
cloudflare_account_id: "{{ cloudflare_account_id }}"
tunnel_name: "home-edge"
terraform_dir: /opt/terraform/cloudflared # Path to Terraform working directory containing .tfstate
cloudflared_bin_path: /usr/local/bin/cloudflared
# Hostname/service mapping for ingress
cloudflared_ingress:
  - hostname: proxy.timmos.com.au
    service: http://localhost:80
  - service: http_status:404
  



cloudflare_zone: "{{ cloudflare_zone }}"
cloudflared_config_path: /etc/cloudflared/config.yml
cloudflared_tunnel_id: ""                # From Terraform output
cloudflared_tunnel_credentials_json: ""  # From Terraform output (JSON string)
cloudflared_service_name: cloudflared


#### WHICH OF THESE IS STILL REQUIRED?



