cloudflare_api_token: "{{ cloudflare_api_token }}"
cloudflare_account_id: "{{ cloudflare_account_id }}"
cloudflare_zone: "{{ cloudflare_zone }}"

cloudflare_access_apps:
  - name: "Sonarr"
    domain: "sonarr.timmos.com.au"
    local_service: "http://192.168.1.100:8989"
    email: "internet@timmos.com.au"
  - name: "Radarr"
    domain: "radarr.timmos.com.au"
    local_service: "http://192.168.1.100:7878"
    email: "internet@timmos.com.au"
