---

- name: Detect accounts with blank passwords
  shell: |
    awk -F: '($2=="") {print $1}' /etc/shadow
  register: empty_pw
  changed_when: false

- name: Lock accounts with blank passwords (defense-in-depth)
  user:
    name: "{{ item }}"
    password_lock: yes
  loop: "{{ empty_pw.stdout_lines }}"
  when: empty_pw.stdout | length > 0

- name: "BLANK PASSWORDS | remove nullok from common-auth"
  replace:
    path: /etc/pam.d/common-auth
    regexp: '\bnullok\b'
    replace: ''
