---
        # -------------------------------------------------------------------
        # Ubuntu 24.04 LTS — DISA-STIG | account_identity | disable_blank_passwords.yml
        # Guarded by variable: enable_disable_blank_passwords
        # -------------------------------------------------------------------

- name: Detect accounts with blank passwords
  command: awk -F: '($2=="" ) {print $1}' /etc/shadow
  register: empty_pw
  changed_when: false

- name: Lock accounts with blank passwords (defense-in-depth)
  user:
    name: "{{ item }}"
    password_lock: yes
  loop: "{{ empty_pw.stdout_lines }}"
  when: empty_pw.stdout | length > 0
