---

- name: Ensure pwquality module is present
  apt:
    name: libpam-pwquality
    state: present
    update_cache: yes

- name: Configure password complexity policy (pwquality)
  template:
    src: "{{ role_path }}/account_identity/templates/pwquality.conf.j2"
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: '0644'
  when: enable_pwquality | default(true)
  notify: restart_sshd

- name: Configure password aging and UMASK (login.defs)
  template:
    src: "{{ role_path }}/account_identity/templates/login.defs.j2"
    dest: /etc/login.defs
    owner: root
    group: root
    mode: '0644'

- name: Ensure login.defs password aging and UMASK
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
  loop:
    - { key: 'PASS_MAX_DAYS', value: '{{ pass_max_days | default(365) }}' }
    - { key: 'PASS_MIN_DAYS', value: '{{ pass_min_days | default(1) }}' }
    - { key: 'PASS_MIN_LEN',  value: '{{ pass_min_len  | default(14) }}' }
    - { key: 'PASS_WARN_AGE', value: '{{ password_aging.warn_days | default(7) }}'}
    - { key: 'UMASK',         value: '{{ login_umask   | default("027") }}' }
  when: enable_login_defs | default(true)

- name: Ensure PAM uses SHA-512 with sufficient rounds
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-password
    regexp: '^password\\s+\\[success=1\\s+default=ignore\\]\\s+pam_unix\\.so.*'
    line: 'password [success=1 default=ignore] pam_unix.so obscure sha512 rounds={{ pam_unix_rounds | default(5000) }}'
  when: enable_pam_unix_sha512 | default(true)

- name: "PASSWORD POLICY | useradd INACTIVE (CIS 24085)"
  lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE='
    line: "INACTIVE={{ pw_inactive_days }}"

