---
- name: Ensure libpam-pwquality present
  apt:
    name: libpam-pwquality
    state: present
    update_cache: yes

- name: Enforce password complexity (pwquality)
  template:
    src: "{{ role_path }}/account_identity/templates/pwquality.conf.j2"
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_sshd

- name: Enforce password aging & UMASK (login.defs)
  template:
    src: "{{ role_path }}/account_identity/templates/login.defs.j2"
    dest: /etc/login.defs
    owner: root
    group: root
    mode: '0644'
