---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Disable remote root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    create: yes
    backup: yes
  notify: restart_sshd

- name: Ensure sudo installed
  apt:
    name: sudo
    state: present
