---
galaxy_info:
  role_name: crypto_fips
  description: Ubuntu Pro FIPS enablement
  author: "Tim Davies"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [24.04]
