---
- name: Install AIDE
  apt:
    name: aide
    state: present

- name: Initialize AIDE DB
  command: aideinit
  args:
    creates: /var/lib/aide/aide.db.new

- name: Activate AIDE DB
  command: mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  args:
    creates: /var/lib/aide/aide.db
