---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Ensure cryptsetup present
  apt:
    name: cryptsetup
    state: present

- name: NOTE - Encrypting existing swap/tmp may require rebuild
  debug:
    msg: 'Recommend implementing LUKS and tmp/swap encryption during imaging.'
