- name: Install required packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Download Elastic GPG key
  become: true
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /tmp/elastic-key.asc
    mode: '0644'

- name: Convert Elastic GPG key to keyring format
  become: true
  shell: |
    gpg --dearmor /tmp/elastic-key.asc
    mv /tmp/elastic-key.asc.gpg /usr/share/keyrings/elastic-keyring.gpg
  args:
    executable: /bin/bash


- name: Add Elastic APT repository (version 8.x)
  become: true
  copy:
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    content: 'deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main'
    mode: '0644'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Elasticsearch and Logstash
  become: true
  apt:
    name:
      - elasticsearch
      - logstash
    state: present

- name: Enable and start Elasticsearch
  become: true
  systemd:
    name: elasticsearch
    enabled: true
    state: started

- name: Enable and start Logstash
  become: true
  systemd:
    name: logstash
    enabled: true
    state: started

    
- name: Deploy Logstash pipeline for Beats/syslog
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: "{{ logstash_pipeline_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart logstash

- name: Enable and start Logstash
  ansible.builtin.service:
    name: "{{ logstash_svc }}"
    enabled: yes
    state: started



#- name: Install Elasticsearch
#  become: true
#  apt:
#    name: elasticsearch
#    state: present



#- name: Install Elasticsearch
#  ansible.builtin.apt:
#    name:
#      - "{{ elasticsearch_pkg }}"
#    state: present
#    update_cache: yes

- name: Enable and start Elasticsearch
  become: true
  systemd:
    name: elasticsearch
    enabled: true
    state: started



- name: Ensure elasticsearch group exists
  ansible.builtin.group:
    name: "{{ elasticsearch_group }}"
    system: yes

- name: Ensure elasticsearch user exists (no shell, no home)
  ansible.builtin.user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Deploy elasticsearch.yml (single-node secure-ready)
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_yml_path }}"
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Ensure Elasticsearch log directory exists
  ansible.builtin.file:
    path: "{{ elasticsearch_log_dir }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: '0750'

- name: Ensure Elasticsearch data directory exists
  ansible.builtin.file:
    path: "{{ elasticsearch_data_dir }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: '0750'

- name: Ensure Elasticsearch log files exist with correct ownership and permissions
  become: true
  file:
    path: "{{ elasticsearch_log_file }}"
    state: touch
    owner: root
    group: elasticsearch
    mode: '0644'

- name: Enable and start Elasticsearch
  ansible.builtin.service:
    name: "{{ elasticsearch_svc }}"
    enabled: yes
    state: started