- name: Install required packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
    state: present

- name: Download Elasticsearch GPG key
  become: true
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /usr/share/keyrings/elasticsearch-keyring.gpg
    mode: '0644'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Elasticsearch
  become: true
  apt:
    name: elasticsearch
    state: present



#- name: Install Elasticsearch
#  ansible.builtin.apt:
#    name:
#      - "{{ elasticsearch_pkg }}"
#    state: present
#    update_cache: yes

- name: Enable and start Elasticsearch
  become: true
  systemd:
    name: elasticsearch
    enabled: true
    state: started



- name: Ensure elasticsearch group exists
  ansible.builtin.group:
    name: "{{ elasticsearch_group }}"
    system: yes

- name: Ensure elasticsearch user exists (no shell, no home)
  ansible.builtin.user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Deploy elasticsearch.yml (single-node secure-ready)
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_yml_path }}"
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Ensure Elasticsearch log directory exists
  ansible.builtin.file:
    path: "{{ elasticsearch_log_dir }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: '0750'

- name: Ensure Elasticsearch data directory exists
  ansible.builtin.file:
    path: "{{ elasticsearch_data_dir }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: '0750'

- name: Ensure Elasticsearch log files exist with correct ownership and permissions
  become: true
  file:
    path: "{{ elasticsearch_log_file }}"
    state: touch
    owner: root
    group: elasticsearch
    mode: '0644'

- name: Enable and start Elasticsearch
  ansible.builtin.service:
    name: "{{ elasticsearch_svc }}"
    enabled: yes
    state: started