- name: Install Logstash
  ansible.builtin.apt:
    name:
      - "{{ logstash_pkg }}"
    state: present
    update_cache: yes
    
- name: Deploy Logstash pipeline for Beats/syslog
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: "{{ logstash_pipeline_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart logstash

- name: Enable and start Logstash
  ansible.builtin.service:
    name: "{{ logstash_svc }}"
    enabled: yes
    state: started