---
#- name: Ensure apt cache is up to date
#  ansible.builtin.apt:
#    update_cache: yes
#    cache_valid_time: 3600


- name: Configure Elasticsearch
  import_tasks: elasticsearch.yml

- name: Configure Kibana
  import_tasks: kibana.yml

- name: Configure Wazuh
  import_tasks: wazuh.yml

- name: Configure UFW
  import_tasks: ufw.yml













