##############################################
#🔍 Why it's set to 900 seconds:
#
# 1. FIPS-related kernel changes may cause longer boot times.
# 2. Slow systems or virtual machines might take longer to shut down and restart.
# 3. Post-reboot services (like SSH, networking, or cloud-init) may take time to stabilize before Ansible can reconnect.
# 4. Safety margin: It prevents premature failure in automation pipelines.
###############################################

- name: Reboot if FIPS enabled
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting to apply FIPS kernel settings"
    reboot_timeout: 900
    pre_reboot_delay: 5
    post_reboot_delay: 10
    test_command: whoami
