- name: Download cloudflared
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: /usr/local/bin/cloudflared
    mode: '0755'

- name: Create cloudflared config directory
  file:
    path: /etc/cloudflared
    state: directory
    mode: '0755'

- name: Upload tunnel config
  template:
    src: config.yml.j2
    dest: /etc/cloudflared/config.yml
    mode: '0644'

- name: Register tunnel as systemd service
  copy:
    dest: /etc/systemd/system/cloudflared.service
    content: |
      [Unit]
      Description=Cloudflare Tunnel
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/cloudflared tunnel --config /etc/cloudflared/config.yml run
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target

- name: Enable and start cloudflared
  systemd:
    name: cloudflared
    enabled: yes
    state: started
