- name: Download and add Elasticsearch GPG key
  shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Update apt cache after adding Elasticsearch repo
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Deploy Elasticsearch config
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_yml_path }}"
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started