- name: UFW - allow SIEM/SOC TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
    from: "{{ mgmt_allow_cidrs | join(',') }}"
  loop:
    - { port: "5601" }   # Kibana
    - { port: "9200" }   # Elasticsearch HTTP
    - { port: "5044" }   # Logstash Beats
    - { port: "1514" }   # Wazuh TCP
    - { port: "55000" }  # Wazuh API

- name: UFW - allow Wazuh UDP if needed
  community.general.ufw:
    rule: allow
    port: "1514"
    proto: udp
    from: "{{ mgmt_allow_cidrs | join(',') }}"