---
        # -------------------------------------------------------------------
        # Ubuntu 24.04 LTS — DISA-STIG | software_appcontrol | remove_unnecessary_packages.yml
        # Guarded by variable: enable_remove_unnecessary_packages
        # -------------------------------------------------------------------

- name: Remove unused/insecure packages (tune per environment)
  apt:
    name: [nis, rsh-server, talk, telnet, ldap-utils]
    state: absent
  ignore_errors: yes
