---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Remove unused/insecure packages
  apt:
    name: [nis, rsh-server, talk, telnet, ldap-utils]
    state: absent
  ignore_errors: yes
