---

- name: Remove unused/insecure packages (tune per environment)
  apt:
    name: [nis, rsh-server, talk, telnet, ldap-utils]
    state: absent
  ignore_errors: yes

- name: Ensure prelink is absent
  ansible.builtin.package:
    name: prelink
    state: absent
  when: remove_prelink | default(true)

- name: "SAMBA | ensure present when enabled"
  when: samba_enabled
  apt:
    name: [ 'samba', 'smbd', 'smbclient' ]
    state: present

- name: "SAMBA | ensure absent when disabled (CIS)"
  when: not samba_enabled
  apt:
    name: [ 'samba', 'smbd', 'smbclient' ]
    state: absent
    purge: yes
