
- name: Ensure auditd is installed
  package:
    name: audit
    state: present

- name: Deploy auditd.conf template
  template:
    src: templates/auditd.conf.j2
    dest: "{{ auditd_conf_path }}"
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd

- name: Deploy audit.rules template
  template:
    src: templates/audit.rules.j2
    dest: "{{ audit_rules_path }}"
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd

- name: Set permissions on audit configs
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - "{{ auditd_conf_path }}"
    - /etc/audit/rules.d
  tags: [lockdown, audit]

- name: Secure audit log file and directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('file') }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { path: "/var/log/audit", state: "directory", mode: "0750" }
    - { path: "/var/log/audit/audit.log", mode: "0600" }
  tags: [lockdown, audit]
