# Kibana needs to be downloaded from elasticsearch apt source list
- name: Download and add Elasticsearch GPG key
  shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Update apt cache after adding Elasticsearch repo
  apt:
    update_cache: yes

- name: Install Kibana
  ansible.builtin.apt:
    name:
      - "{{ kibana_pkg }}"
    state: present
    update_cache: yes

- name: Deploy Kibana config
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: "{{ kibana_yml_path }}"
    owner: root
    group: kibana
    mode: '0640'
  notify: restart kibana

- name: Ensure Kibana is stopped before plugin installation
  systemd:
    name: kibana
    state: stopped

- name: Download Wazuh Kibana plugin
  get_url:
    url: "https://packages.wazuh.com/4.x/ui/kibana/wazuh-kibana-plugin-4.7.2_1.zip"
    dest: "/tmp/wazuh-kibana-plugin.zip"

- name: Install Wazuh Kibana plugin
  command: >
    /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuh-kibana-plugin.zip
  args:
    creates: /usr/share/kibana/plugins/wazuh

- name: Start Kibana after plugin installation
  systemd:
    name: kibana
    state: started
    enabled: yes

- name: Enable and start Kibana
  ansible.builtin.service:
    name: "{{ kibana_svc }}"
    enabled: yes
    state: started