- name: Harden SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication yes' }
    - { regexp: '^X11Forwarding', line: 'X11Forwarding no' }

- name: Restart SSH
  service:
    name: ssh
    state: restarted
