- name: Validate Prometheus scrape config
  template:
    src: prometheus_scrape_config.yml.j2
    dest: "{{ prometheus_scrape_config_path }}"
    mode: '0644'

- name: Log Prometheus config directory creation
  lineinfile:
    path: "{{ audit_log_path }}"
    line: "Created /etc/prometheus for scrape config at {{ ansible_date_time.iso8601 }}"
    create: yes

- name: Ensure Prometheus config directory exists
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'
