---
- name: Restore config templates
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ item }}/config/config.xml"
    owner: "{{ item }}"
    group: "{{ media_group }}"
    mode: '0644'
  loop: "{{ servarr_apps + other_apps }}"

- name: Restore database files from backup
  copy:
    src: "{{ backup_base_path }}/{{ item }}/database.db"
    dest: "/home/{{ item }}/config/database.db"
    owner: "{{ item }}"
    group: "{{ media_group }}"
    mode: '0600'
  loop: "{{ servarr_apps + other_apps }}"
