---
- name: Ensure media group exists
  group:
    name: "{{ media_group }}"
    state: present

#- name: Install dependencies
#  apt:
#    name:
#      - curl
#      - gnupg
#      - ca-certificates
#      - software-properties-common
#      - rsync
#    state: present
#    update_cache: yes
#    install_recommends: no

#- name: Create mount points
#  include_tasks: mount_points.yml

#- name: Install Servarr apps
#  include_tasks: servarr.yml
  
- name: Install qBittorrent-nox
  include_tasks: qbittorrent.yml

#- name: Install Kodi
#  include_tasks: kodi.yml

#- name: Install Huntarr
#  include_tasks: huntarr.yml

#- name: Establish backup routine
#  include_tasks: backup.yml






