---
- name: Ensure media group exists
  group:
    name: "{{ media_group }}"
    state: present

- name: Create users for non-servarr apps
  user:
    name: "{{ item }}"
    group: "{{ media_group }}"
    shell: /usr/sbin/nologin
    create_home: yes
  loop: 
    - "{{ other_apps }}"
  # loop: "{{ servarr_apps + other_apps }}"
  
- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - software-properties-common
      - xinit
      - git
      - python3
      - python3-venv
      - python3-pip
      - xorg
      - dbus-x11
      - xserver-xorg-video-intel
      - xserver-xorg-legacy
      - pulseaudio
      - upower
      - samba
      - cifs-utils
      - rsync
    state: present
    update_cache: yes
    install_recommends: no

#- name: Create mount points
#  include_tasks: mount_points.yml

#- name: Install Servarr apps
#  include_tasks: servarr.yml
  
#- name: Install qBittorrent-nox
#  include_tasks: qbittorrent.yml

- name: Install Kodi
  include_tasks: kodi.yml

#- name: Install Huntarr
#  include_tasks: huntarr.yml








