- name: Install dependencies
  apt:
    name:
      - samba
      - cifs-utils
    state: present
    update_cache: yes
    install_recommends: no

- name: Create CIFS credentials file
  copy:
    dest: /etc/smb_credentials
    content: |
      username={{ username }}
      password={{ password }}
    owner: root
    group: root
    mode: '0600'

- name: Ensure mount points exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: media
    mode: '0755'
  loop:
    - /mnt/data
    - /mnt/r

- name: Ensure CIFS mount entries are present in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^//192\\.168\\.1\\.106/data\\s+/mnt/data\\s+cifs\\s+.*$', line: '//192.168.1.106/data /mnt/data cifs credentials=/etc/smb_credentials,x-systemd.automount,rw,uid=1000,gid=1001,file_mode=0664,dir_mode=0775,vers=3.0,sec=ntlmssp,nodfs 0 0' }
    - { regexp: '^//192\\.168\\.1\\.106/r\\s+/mnt/r\\s+cifs\\s+.*$', line: '//192.168.1.106/r /mnt/r cifs credentials=/etc/smb_credentials,x-systemd.automount,rw,uid=1000,gid=1001,file_mode=0664,dir_mode=0775,vers=3.0,sec=ntlmssp,nodfs 0 0' }
###################
### TODO: make gid dynamic
##################
- name: Mount CIFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: cifs
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    - {
        path: "/mnt/data",
        src: "//192.168.1.106/data",
        opts: "credentials=/etc/smb_credentials,x-systemd.automount,rw,uid=1000,gid=1000,file_mode=0664,dir_mode=0775,vers=3.0,sec=ntlmssp,nodfs"
      }
    - {
        path: "/mnt/r",
        src: "//192.168.1.106/r",
        opts: "credentials=/etc/smb_credentials,x-systemd.automount,rw,uid=1000,gid=1000,file_mode=0664,dir_mode=0775,vers=3.0,sec=ntlmssp,nodfs"
      }

- name: Restrict Samba to SMBv2 and SMBv3 only
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [global]
      server min protocol = SMB2
      server max protocol = SMB3
  notify: restart samba