# Install qBittorrent
- name: Install qBittorrent-nox
  apt:
    name: qbittorrent-nox
    state: present
    update_cache: true

- name: Restore from config template
  template:
    src: "qbittorrent.{{ files }}.j2"
    dest: "/home/qbittorrent-nox/.config/qBittorrent/{{ files }}"
    owner: "qbittorrent-nox"
    group: "{{ media_group }}"
    mode: '0644'
  loop:
    files:
      - settings.json
      - categories.json
      - qBittorrent-data.conf
      - qBittorrent.conf
      - watched_folders.json

- name: Create systemd service for qBittorrent
  template:
    src: qbittorrent.service.j2
    dest: /etc/systemd/system/qbittorrent-nox.service
    mode: '0644'

- name: Enable and start qBittorrent service
  systemd:
    name: qbittorrent-nox
    enabled: yes
    state: started