#- name: Install Servarr apps using tinyoverflow role
#  include_role:
#    name: tinyoverflow.servarr
#  vars:
#    servarr_app: "{{ item }}"
#    servarr_user: "{{ item }}"
#    servarr_group: "{{ media_group }}"
#    servarr_instance_name: "default"
#  loop: "{{ servarr_apps }}"

# Update app configurations and databases from backups

- name: Restore config files
  copy:
    src: "/mnt/data/servarr/{{ item }}/config.xml"
    dest: "{{ backup_base_path }}/{{ item }}/default/config.xml"
    owner: "{{ item }}"
    group: "{{ media_group }}"
    mode: '0644'
    remote_src: yes
  loop: "{{ servarr_apps }}"


- name: Restore database files from backup
  copy:
    src: "/mnt/data/servarr/{{ item }}/{{ item }}.db"
    dest: "{{ backup_base_path }}/{{ item }}/default/{{ item }}.db"
    owner: "{{ item }}"
    group: "{{ media_group }}"
    mode: '0644'
    remote_src: yes
  loop: "{{ servarr_apps }}"