- name: Reload systemd
  command: systemctl daemon-reexec

#- name: restart samba
#  ansible.builtin.service:
#    name: samba
#    state: restarted

- name: restart smbd
  service:
    name: smbd
    state: restarted

- name: Enable cron service
  ansible.builtin.systemd:
    name: cron
    enabled: yes

- name: Start cron service
  ansible.builtin.systemd:
    name: cron
    state: started
