- name: Reload systemd
  command: systemctl daemon-reexec

#- name: restart samba
#  ansible.builtin.service:
#    name: samba
#    state: restarted

- name: restart smbd
  service:
    name: smbd
    state: restarted