- name: Ensure cifs-utils is installed
  apt:
    name: cifs-utils
    state: present
    update_cache: yes

- name: Create mount point
  file:
    path: /mnt/data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create CIFS credentials file
  copy:
    dest: /etc/samba/creds-tim
    content: |
      username=tim
      password=1212
    owner: root
    group: root
    mode: '0600'

- name: Ensure CIFS entry is present in fstab
  mount:
    path: /mnt/data
    src: //192.168.1.106/data
    fstype: cifs
    opts: credentials=/etc/samba/creds-tim,iocharset=utf8,file_mode=0777,dir_mode=0777,nofail
    state: mounted


- name: Copy file to mounted share
  copy:
    src: /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords.txt
    dest: /mnt/data/wazuh-passwords.txt
    remote_src: yes

