---

- name: Enforce secure ownership/permissions on critical auth files
  file:
    path: "{{ item.path }}"
    owner: root
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /etc/gshadow,  group: shadow, mode: '0600' }
    - { path: /etc/gshadow-, group: shadow, mode: '0600' }
    - { path: /etc/shadow,   group: shadow, mode: '0600' }
    - { path: /etc/shadow-,  group: shadow, mode: '0600' }
    - { path: '/etc/passwd', group: shadow, mode: '0644' }
    - { path: '/etc/group', group: shadow, mode: '0644' }
