#####################################################
# Upgrade firewall application
#####################################################
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Disable ufw if service exists
  service:
    name: ufw
    state: stopped
    enabled: no
  when: "'ufw' in ansible_facts.services"

- name: Install nftables
  apt:
    name: nftables
    state: present

###################################################
# Copy across applicable ruleset
###################################################
- name: Configure rules for SIEM Server configuration
  template:
    src: baseline_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "baseline"

- name: Configure rules for Cloudflared/NGINX Reverse Proxy configuration
  template:
    src: nginx_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "reverse_proxy"

- name: Configure rules for SIEM Server configuration
  template:
    src: siem_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "siem"

- name: Configure rules for Ubuntu Desktop configuration
  template:
    src: desktop_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "ubuntu_desktop"

- name: Configure rules for Servarr configuration
  template:
    src: servarr_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "servarr"

###########################################
# Start nftables and apply ruleset
###########################################
- name: Enable and start nftables service
  systemd:
    name: nftables
    enabled: true
    state: started

- name: Apply nftables ruleset
  command: nft -f /etc/nftables.conf
  become: true
