- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set default policies
  become: true
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH
  become: true
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - allow SIEM/SOC TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
    from: "{{ mgmt_allow_cidrs | join(',') }}"
  loop:
    - { port: "5601" }  # Kibana
    - { port: "9200" }  # Elasticsearch HTTP
    - { port: "9300" }  # Elasticsearch HTTP
    - { port: "5044" }  # Logstash Beats
    - { port: "1514" }  # Wazuh TCP
    - { port: "1515" }  # Wazuh TCP
    - { port: "1516" }  # Wazuh TCP
    - { port: "55000" } # Wazuh API
    - { port: "541" }   # Wazuh Dashboard
    - { port: "9090" }  # Prometheus
    - { port: "3000" }  # Grafana
    - { port: "514" }   # Syslog TCP
    - { port: "443" }   # Wazuh Dashboard port

- name: UFW - allow SIEM/SOC UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
    from: "{{ mgmt_allow_cidrs | join(',') }}"
  loop:
    - { port: "514" }  # Syslog UDP
    - { port: "1514" }  # Wazuh UDP

