- name: Install nftables
  apt:
    name: nftables
    state: present


- name: Configure rules for Cloudflared/NGINX Reverse Proxy configuration
  template:
    src: nginx_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "reverse_proxy"

- name: Configure rules for SIEM Server configuration
  template:
    src: siem_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "siem"

- name: Configure rules for Ubuntu Desktop configuration
  template:
    src: desktop_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "ubuntu_desktop"

- name: Configure rules for Servarr configuration
  template:
    src: servarr_nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  when: ruleset == "servarr"

- name: Enable and start nftables service
  systemd:
    name: nftables
    enabled: true
    state: started

- name: Apply nftables ruleset
  command: nft -f /etc/nftables.conf
  become: true




# old CONFIG USING ufw
#- name: Install UFW
#  apt:
#    name: ufw
#    state: present

#- name: Set default policies
#  become: true
#  ufw:
#    state: enabled
#    policy: deny
#    direction: incoming

#- name: Allow SSH
#  become: true
#  ufw:
#    rule: allow
#    name: OpenSSH

#- name: UFW - allow SIEM/SOC TCP ports
#  community.general.ufw:
#    rule: allow
#    port: "{{ item.port }}"
#    proto: tcp
#    from: "{{ mgmt_allow_cidrs | join(',') }}"
#  loop: "{{ siem_ports }}"
#  vars:
#    siem_ports:
#      - { port: "5601" }  # Kibana Web interface
#      - { port: "9200" }  # Indexer API (used by Kibana and Filebeat)
#      - { port: "9300" }  # Internal cluster communication (multi-node setups)
#      - { port: "5044" }  # Logstash Beats
#      - { port: "1514" }  # Wazuh Agent event reporting
#      - { port: "1515" }  # Wazuh Agent registration
#      - { port: "1516" }  # Wazuh Cluster communication (if using multi-node setup)
#      - { port: "55000" } # Wazuh REST API (used by Dashboard and integrations)
#      - { port: "541" }   # Wazuh Dashboard
#      - { port: "9090" }  # Prometheus
#      - { port: "3000" }  # Grafana
#      - { port: "514" }   # Syslog TCP
#      - { port: "443" }   # Wazuh Dashboard port

#- name: Open http tcp ports 9200 to 9299 on UFW
#  community.general.ufw:
#    rule: allow
#    port: "9200:9299"
#    proto: tcp
#  become: true


#- name: Open transport tcp ports 9300 to 9399 on UFW
#  community.general.ufw:
#    rule: allow
#    port: "9300:9399"
#    proto: tcp
#  become: true

#- name: UFW - allow SIEM/SOC UDP ports
#  community.general.ufw:
#    rule: allow
#    port: "{{ item.port }}"
#    proto: tcp
#    from: "{{ mgmt_allow_cidrs | join(',') }}"
#  loop:
#    - { port: "514" }  # Syslog UDP
#    - { port: "1514" }  # Wazuh UDP

