- name: Install Prometheus Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract and install
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      ExecStart=/opt/node_exporter-1.6.1.linux-amd64/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd
