---
- name: Install auditd and plugins
  apt:
    name: [auditd, audispd-plugins]
    state: present
    update_cache: yes

- name: Enable and start auditd
  systemd:
    name: auditd
    enabled: yes
    state: started
