---
- name: Create Ubuntu Pro attach config file
  copy:
    content: |
      token: "{{ ubuntu_pro_token }}"
      enable_services:
        - usg
    dest: /tmp/pro-attach-config.yaml
    mode: '0600'

- name: Attach to Ubuntu Pro using config file
  command: pro attach --attach-config /tmp/pro-attach-config.yaml
  register: pro_attach_result
  changed_when: "'already attached' not in pro_attach_result.stdout"
