---
- name: Ensure 'pro' CLI is installed
  apt:
    name: ubuntu-advantage-tools
    state: present
    update_cache: yes

- name: Check current Ubuntu Pro status
  command: pro status --format json
  register: pro_status_raw
  changed_when: false

- name: Parse Ubuntu Pro status
  set_fact:
    pro_status: "{{ pro_status_raw.stdout | from_json }}"

- name: Log current attachment status
  debug:
    msg: "System is currently attached to: {{ pro_status.account.email | default('UNATTACHED') }}"

- name: Include attach logic only if system is not already attached
  include_tasks: "{{ role_path }}/tasks/attach.yml"
  when: pro_status.account.email is not defined or pro_status.account.email | trim == ''

- name: Skip Ubuntu Pro attach if already attached
  debug:
    msg: "System already attached to {{ pro_status.account.email }}. Skipping attach and config creation."
  when: pro_status.account.email | default('') != ''

- name: Include attach tasks only if not already attached
  include_tasks: "{{ role_path }}/tasks/attach.yml"
  when: pro_status.account.email | default('') == ''

- name: Skip USG enablement if already active
  debug:
    msg: "USG already enabled. Skipping."
  when: "'usg' in pro_status.enabled_services"

- name: Enable USG (Ubuntu Security Guide)
  command: pro enable usg
  register: usg_enable
  changed_when: "'enabled' in usg_enable.stdout"
  when: "'usg' not in pro_status.enabled_services"

- name: Save Ubuntu Pro status to audit log
  copy:
    content: "{{ pro_status_raw.stdout }}"
    dest: /var/log/ubuntu-pro-status.json
    mode: '0640'

- name: Show final Ubuntu Pro status
  command: pro status
  register: final_status
  changed_when: false

- name: Display final status
  debug:
    var: final_status.stdout
