- name: Install Wazuh Agent on Ubuntu 24.04 Desktop
  hosts: all
  become: yes
  gather_facts: yes  # Ensures we retrieve the system hostname

  tasks:
    - name: Download Wazuh Agent .deb package
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.13.1-1_amd64.deb
        dest: /tmp/wazuh-agent_4.13.1-1_amd64.deb

    - name: Install Wazuh Agent with environment variables
      ansible.builtin.command:
        cmd: >
          dpkg -i /tmp/wazuh-agent_4.13.1-1_amd64.deb
        chdir: /tmp
      environment:
        WAZUH_MANAGER: "192.168.1.240"
        WAZUH_AGENT_GROUP: "default"
        WAZUH_AGENT_NAME: "{{ ansible_facts['hostname'] }}"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable wazuh-agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start wazuh-agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started