---
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600


#- name: Configure Suricata
#  import_tasks: suricata.yml

#- name: Configure Prometheus
#  import_tasks: prometheus.yml

#- name: Configure Grafana
#  import_tasks: grafana.yml

#- name: Configure Zeek
#  import_tasks: zeek.yml

#- name: Configure Wazuh
#  import_tasks: wazuh.yml

#- name: Configure rSyslog
#  import_tasks: rsyslog.yml

#- name: Configure UFW
#  import_tasks: ufw.yml

#- name: Install monitoring packages
#  ansible.builtin.apt:
#    name:
#      - "{{ suricata_pkg }}"
#      - "{{ zeek_pkg }}"
#      - "{{ ossec_pkg }}"
#      - "{{ prometheus_pkg }}" 
#      - "{{ node_exporter_pkg }}"
#      - "{{ grafana_pkg }}"
#      - "{{ rsyslog_pkg }}"
#      - "{{ ufw_pkg }}"
#    state: present

- name: Install CIFS utilities
  apt:
    name: cifs-utils
    state: present
    update_cache: yes

- name: Create mount point
  file:
    path: /mnt/remote_data
    state: directory

- name: Ensure mount point exists
  file:
    path: /mnt/remote_data
    state: directory

- name: Add CIFS mount entry to /etc/fstab
  blockinfile:
    path: /etc/fstab
    block: |
      # CIFS mount for Elasticsearch backup
      //192.168.1.106/data /mnt/remote_data cifs guest,nounix,noserverino,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0

- name: Mount CIFS share
  command: mount /mnt/remote_data
  args:
    warn: false

- name: Copy elasticsearch.yml to mounted share
  copy:
    src: /etc/elasticsearch/elasticsearch.yml
    dest: /mnt/remote_data/elasticsearch.yml
    remote_src: yes


#- name: Copy elasticsearch.yml to CIFS share
#  copy:
#    src: /etc/elasticsearch/elasticsearch.yml
#    dest: /mnt/remote_data/elasticsearch.yml
#    remote_src: yes











