- name: Install Suricata
  apt:
    name: suricata
    state: present
    update_cache: yes

- name: Deploy Suricata configuration
  template:
    src: suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Suricata service
  systemd:
    name: suricata
    enabled: yes
    state: started
