- name: Install UFW
  ansible.builtin.apt:
    name:
      - "{{ ufw_pkg }}"
    state: present

- name: UFW - ensure enabled with default deny inbound
  community.general.ufw:
    state: enabled
    policy: "{{ ufw_default_input_policy }}"

- name: UFW - allow required TCP service ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    from: "{{ mgmt_allow_cidrs | join(',') }}"
  loop: "{{ ufw_allowed_tcp_ports }}"

- name: UFW - allow required UDP service ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    from: "{{ mgmt_allow_cidrs | join(',') }}"
  loop: "{{ ufw_allowed_udp_ports }}"

