- name: Install Wazuh Indexer
  apt:
    name: wazuh-indexer={{ wazuh_version }}
    state: present
  when: ansible_os_family == "Debian"

- name: Configure JVM memory
  lineinfile:
    path: /etc/wazuh-indexer/jvm.options
    regexp: '^(-Xms|-Xmx)'
    line: "-Xms1024m"
  notify: restart wazuh-indexer

- name: Copy certificates
  copy:
    src: files/indexer.pem
    dest: /etc/wazuh-indexer/certs/indexer.pem
    owner: wazuh-indexer
    mode: '0400'

- name: Start Wazuh Indexer
  systemd:
    name: wazuh-indexer
    enabled: yes
    state: started
