- name: Install required dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    state: present
    update_cache: yes

- name: Download and add Wazuh GPG key
  shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/wazuh-archive-keyring.gpg

- name: Add Wazuh repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wazuh-archive-keyring.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Wazuh manager
  apt:
    name: wazuh-manager
    state: present

- name: Install Wazuh dashboard
  apt:
    name: wazuh-dashboard
    state: present

- name: Enable and start Wazuh manager
  systemd:
    name: wazuh-manager
    enabled: yes
    state: started

- name: Enable and start Wazuh dashboard
  systemd:
    name: wazuh-dashboard
    enabled: yes
    state: started



