---
- name: Create servarr system group
  become: true
  ansible.builtin.group:
    name: "{{ servarr_group }}"
    system: true

- name: Create servarr system user
  become: true
  ansible.builtin.user:
    name: "{{ servarr_user }}"
    group: "{{ servarr_group }}"
    shell: /usr/sbin/nologin
    home: "{{ _release_install_dir }}"
    system: true
    create_home: false
