---
- name: Install systemd service
  become: true
  ansible.builtin.template:
    src: "templates/etc/systemd/system/servarr.service.j2"
    dest: "/etc/systemd/system/{{ _instance_service_name }}.service"
    mode: "0644"
  notify: Restart servarr


- name: Check if whisparr2.service file exists
  ansible.builtin.stat:
    path: /etc/systemd/system/whisparr2-default.service
  register: whisparr2_service_file

- name: Ensure Whisparr ExecStart uses Whisparr not Whisparr2
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/whisparr2-default.service
    regexp: '^ExecStart=/opt/whisparr2/Whisparr2 -nobrowser -data=/var/lib/whisparr2/default$'
    line: 'ExecStart=/opt/whisparr2/Whisparr -nobrowser -data=/var/lib/whisparr2/default'
    backup: no
    create: no
  when: whisparr2_service_file.stat.exists
  notify: Reload systemd


- name: Enable services
  become: true
  ansible.builtin.systemd:
    name: "{{ _instance_service_name }}"
    enabled: true
    state: started
    masked: false
