---
# network_security control group — included by baseline/tasks/main.yml

- name: Run ufw firewall
  import_tasks: ufw_firewall.yml
  when: enable_ufw_firewall


- name: Run ssh hardening
  import_tasks: ssh_hardening.yml
  when: enable_ssh_hardening


- name: Run disable unused protocols
  import_tasks: disable_unused_protocols.yml
  when: enable_disable_unused_protocols
