- name: Ensure UFW present
  apt:
    name: ufw
    state: present

- name: Set default deny inbound policy
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Set default allow outbound policy
  ufw:
    policy: allow
    direction: outgoing

- name: Allow SSH on configured port
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: FIREWALL | ensure only UFW is active
  service: { name: nftables, enabled: no, state: stopped }
  ignore_errors: yes

- name: FIREWALL | default deny inbound, allow outbound
  block:
    - ufw: { state: enabled, direction: incoming, policy: deny }
    - ufw: { direction: routed, policy: deny }
    - ufw: { direction: outgoing, policy: allow }

- name: FIREWALL | loopback rules
  block:
    - ufw: { rule: allow, interface: lo, direction: in }
    - ufw: { rule: deny, src: 127.0.0.0/8, direction: in }

- name: FIREWALL | allow required inbound ports (SSH only by default)
  ufw:
    rule: allow
    port: "{{ item.split('/') [0] }}"
    proto: "{{ item.split('/') [1] }}"
  loop: "{{ ufw_allowed_ports }}"
