---
- name: Ensure UFW present
  apt:
    name: ufw
    state: present

- name: Default deny inbound
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Default allow outbound
  ufw:
    policy: allow
    direction: outgoing

- name: Allow SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
