---
# This task is part of Ubuntu 24.04 LTS DISA-STIG baseline

- name: Enforce signed repositories only
  lineinfile:
    path: /etc/apt/apt.conf.d/99verify
    line: 'Acquire::AllowInsecureRepositories "false";'
    create: yes
