#- name: Install Prometheus
#  become: true
#  apt:
#    name: prometheus
#    state: present
#    update_cache: yes

#- name: Ensure Prometheus is running
#  become: true
#  service:
#    name: prometheus
#    state: started
#    enabled: yes



- name: Install Prometheus
  ansible.builtin.apt:
    name:
      - "{{ prometheus_pkg }}" 
    state: present



- name: Deploy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus

- name: Install Prometheus alert rules
  ansible.builtin.copy:
    src: prometheus_alert_rules.yml
    dest: /etc/prometheus/alert_rules.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus

- name: Enable and start Prometheus
  ansible.builtin.service:
    name: "{{ prometheus_svc }}"
    enabled: yes
    state: started