- name: Ensure media group exists
  group:
    name: media
    state: present

- name: Create qbittorrent users
  user:
    name: "{{ item }}"
    group: media
    shell: /usr/sbin/nologin
    create_home: yes
    state: present
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Install qbittorrent-nox
  apt:
    name: qbittorrent-nox
    state: present
    update_cache: yes

- name: Create config directories
  file:
    path: "/home/{{ item }}/.config/qBittorrent"
    state: directory
    owner: "{{ item }}"
    group: media
    mode: '0755'
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Deploy config files from templates
  template:
    src: "{{ item }}.conf.j2"
    dest: "/home/{{ item }}/.config/qBittorrent/qBittorrent.conf"
    owner: "{{ item }}"
    group: media
    mode: '0644'
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Deploy categories files from templates
  template:
    src: "{{ item }}.categories.json.j2"
    dest: "/home/{{ item }}/.config/qBittorrent/categories.json"
    owner: "{{ item }}"
    group: media
    mode: '0644'
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Deploy categories files from templates
  template:
    src: "{{ item }}.watched_folders.json.j2"
    dest: "/home/{{ item }}/.config/qBittorrent/watched_folders.json"
    owner: "{{ item }}"
    group: media
    mode: '0644'
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Deploy systemd service files
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  loop:
    - qbittorrent1
    - qbittorrent2

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start qbittorrent services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - qbittorrent1
    - qbittorrent2
