galaxy_info:
  author: T
  description: Provision Cloudflare Access apps for self-hosted services
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - cloud
    - security
    - networking
dependencies: []
