galaxy_info:
  role_name: cloudflared
  author: T
  description: Automates Cloudflare Origin CA certificate issuance using Terraform and installs it securely
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - cloud
    - security
    - networking
dependencies: []
