---
- name: Install essential packages
  apt:
    name:
      - ubuntu-advantage-tools
    state: present
    
- name: Attach Ubuntu Pro (if token provided)
  ansible.builtin.command: "pro attach {{ ubuntu_pro_token }}"
  args:
    creates: /var/lib/ubuntu-advantage/private/machine-token.json
  when: (enable_fips or enable_usg) and ubuntu_pro_token | length > 0
  register: pro_attach
  changed_when: pro_attach.rc == 0 and ('Attached' in (pro_attach.stdout | default('')) or 'This machine is already attached' not in (pro_attach.stdout | default('')))
  tags: [fips]

- name: Get Ubuntu Pro status
  ansible.builtin.command: pro status --format=json
  register: pro_status
  changed_when: false
  when: enable_fips
  tags: [fips]

- name: Enable FIPS updates
  ansible.builtin.command: pro enable fips-updates --assume-yes
  register: fips_enable
  changed_when: fips_enable.rc == 0 and ('Enabled' in (fips_enable.stdout | default('')))
  failed_when: >
    fips_enable.rc != 0 and
    ('FIPS Updates is already enabled' not in (fips_enable.stdout | default('')))
  when: 
    - enable_fips
    - ((pro_status.stdout | from_json).services | selectattr('name', 'equalto', 'fips-updates') | map(attribute='status') | first | default('disabled')) != 'enabled'
  tags: [fips]

- name: Enable USG updates
  ansible.builtin.command: pro enable usg --assume-yes
  register: usg_enable
  changed_when: usg_enable.rc == 0 and ('Enabled' in (usg_enable.stdout | default('')))
  failed_when: >
    usg_enable.rc != 0 and
    ('USG is already enabled' not in (usg_enable.stdout | default('')))
  when: 
    - enable_usg
    - ((pro_status.stdout | from_json).services | selectattr('name', 'equalto', 'usg') | map(attribute='status') | first | default('disabled')) != 'enabled'
  tags: [usg]
  
- name: Reboot required for FIPS enable
  ansible.builtin.reboot:
    msg: "Rebooting to load FIPS kernel"
    reboot_timeout: 900
  when: enable_fips and (fips_enable is changed)
  tags: [fips]
