stig_enabled_tags:
  - auditd
  - ssh
  - pam
  - banner
  - cron
  - fips
  - ctrl_alt_del
  - file_permissions

ubuntu24stig_disruption_high: false
ubtu24stig_run_audit: true
ubuntu_pro_token: "{{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"
