---
- name: Ensure SSH server installed
  ansible.builtin.package:
    name: "{{ sshd_pkg }}"
    state: present
  tags: [ssh, ssh_hardening]

- name: Render sshd_config (validated before restart)
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ sshd_config_path }}"
    owner: root
    group: root
    mode: "0600"
  notify: Validate and restart sshd safely
  tags: [ssh, ssh_hardening]
