---
- name: Provision New Ubuntu 24.04 Server
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

  roles:
    - role: ubuntu_pro_attach
      vars:
        ubuntu_pro_token: "{{ ubuntu_pro_token }}"
    - role: users           # Create admin user and SSH keypair
    - role: common          # Update apt cach and packages, and set timezone
    - role: packages        # Install essential packages
    - role: ssh
    
