---
- name: Provision New Ubuntu 24.04 Server
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - group_vars/all.yml
  collections:
    - community.general

  roles:
    - role: baseline
#    - role: baseline/packages            # Install essential packages
#    - role: baseline/time_sync
#    - role: baseline/network_security
#    - role: baseline/ssh_hardening          # requires playbook restart
#    - role: baseline/file_integrity_audit
#    #- role: baseline/auth_access
#    - role: baseline/crypto_fips           # Requires restart if FIPS is not already enabled
#    - role: baseline/logging_journal
#    - role: baseline/system_hardening
#    - role: baseline/session_timeouts
#    - role: baseline/packages_patching
#    - role: baseline/compliance_lockdown
#    - role: firewall                # Install nftables and configure
#      vars:
#        ruleset: "baseline"

