---
- name: Provision New Ubuntu 24.04 Server
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - group_vars/all.yml
  collections:
    - community.general

  roles:
    - role: packages            # Install essential packages
    - role: time_sync
    - role: network_security
    - role: ssh_hardening          # requires playbook restart
    - role: file_integrity_audit
    #- role: auth_access
    - role: crypto_fips           # Requires restart if FIPS is not already enabled
    - role: logging_journal
    - role: system_hardening
    - role: session_timeouts
    - role: packages_patching
    - role: compliance_lockdown
