---
- name: Full STIG-Compliant Provisioning for Ubuntu 24.04
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml

- name: Confirm Ansible context
  hosts: all
  gather_facts: false
  tasks:
    - name: Show inventory_dir
      debug:
        var: inventory_dir

    - name: Show playbook_dir
      debug:
        var: playbook_dir
        
- name: Confirm group_vars loading
  hosts: all
  gather_facts: false
  tasks:
    - name: Show STIG tags
      debug:
        var: stig_enabled_tags

  roles:
    - role: hardening       # Apply full STIG controls
    - role: firewall
    - role: ssh