---
- name: Full STIG-Compliant Provisioning for Ubuntu 24.04
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

- name: Confirm Ansible context  ### Some debug tasks to check things are in place. Can be removed.
  hosts: all
  gather_facts: false
  tasks:
    - name: Show inventory_dir
      debug:
        var: inventory_dir

    - name: Show playbook_dir
      debug:
        var: playbook_dir
    - name: Show STIG tags
      debug:
        var: stig_enabled_tags

  roles:
    - role: hardening       # Apply full STIG controls
    - role: firewall
    - role: ssh             # Harden SSH implementation if not doone during provisioning.
