---
- name: Configure NGINX as reverse proxy through Cloudflare Tunnel
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

  roles:
    - role: reverse_proxy/nginx           # Hardened reverse proxy on loopback
    - role: reverse_proxy/cloudflared     # Secure outbound tunnel to Cloudflare
    - role: firewall                      # Install nftables and configure
      vars:
        ruleset: "reverse_proxy"

