---
- name: Install and configure media automation stack
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - group_vars/all.yml
  collections:
    - community.general

  roles:
    - role: firewall                # Install nftables and configure
      vars:
        ruleset: "servarr"
    #- role: servarr_stack           # Install and configure applications


