---
- name: DoD Monitoring & SIEM/SOC setup (Ubuntu 24.04)
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars_files:
  - group_vars/monitoring/main.yml
  vars:
    single_node: true
    minimum_master_nodes: 1
    indexer_node_master: true
    indexer_network_host: "{{ server_ip }}"
    filebeat_node_name: node-1
    filebeat_output_indexer_hosts:
    - "{{ server_ip }}"
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: "{{ server_ip }}"
        role: indexer
    ansible_shell_allow_world_readable_temp: true

  roles:
    - role: firewall
      vars:
        ruleset: "siem"
    - role: siem/logstash
    - role: ../roles/siem/wazuh/wazuh-indexer
    - role: ../roles/siem/wazuh/ansible-wazuh-manager
    - role: ../roles/siem/wazuh/ansible-filebeat-oss
    - role: ../roles/siem/wazuh/wazuh-dashboard
    - role: siem/suricata
    - role: siem/prometheus
    - role: siem/grafana
    - role: siem/validate_siem
