---
- name: DoD Monitoring & SIEM/SOC setup (Ubuntu 24.04)
  hosts: all
  become: yes
    vars_files:
    - group_vars/monitoring/main.yml

  roles:
    - role: monitoring_setup
    - role: siem_soc_setup
