---
#- name: DoD Monitoring & SIEM/SOC setup (Ubuntu 24.04)
#  hosts: all
#  become: yes
#  vars_files:
#  - group_vars/monitoring/main.yml

#  roles:
#    - role: monitoring_setup
#    - role: siem_soc_setup

# Certificates generation
#- hosts: all
#  roles:
#    - role: ../roles/wazuh/wazuh-indexer
#      perform_installation: false
#  become: no
#  #become_user: root
#  vars_files:
#    - group_vars/monitoring/main.yml
#  vars:
#    indexer_node_master: true
#    instances:
#      node1:
#        name: node-1       # Important: must be equal to indexer_node_name.
#        ip: "{{ server_ip }}"
#        role: indexer
#  tags:
#    - generate-certs

# Single node
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: ../roles/wazuh/wazuh-indexer
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat-oss
    - role: ../roles/wazuh/wazuh-dashboard
  vars_files:
    - group_vars/monitoring/main.yml
  vars:
    single_node: true
    minimum_master_nodes: 1
    indexer_node_master: true
    indexer_network_host: "{{ server_ip }}"
    filebeat_node_name: node-1
    filebeat_output_indexer_hosts:
    - "{{ server_ip }}"
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: "{{ server_ip }}"
        role: indexer
    ansible_shell_allow_world_readable_temp: true
