---
- name: Install systemd service
  become: true
  ansible.builtin.template:
    src: "templates/etc/systemd/system/servarr.service.j2"
    dest: "/etc/systemd/system/{{ _instance_service_name }}.service"
    mode: "0644"
  notify: Restart servarr

- name: Enable services
  become: true
  ansible.builtin.systemd:
    name: "{{ _instance_service_name }}"
    enabled: true
    state: started
    masked: false
