---
# Role defaults (override in group_vars/monitoring/main.yml as needed)

# Package names (Ubuntu 24.04)
suricata_pkg: suricata
suricata_config_path: /etc/suricata/suricata.yaml
suricata_svc: suricata
# --- Suricata service account & paths (recap / ensure present) ---
suricata_user: suricata
suricata_group: suricata
suricata_log_dir: /var/log/suricata
suricata_log_json: /var/log/suricata/eve.json
suricata_log_log: /var/log/suricata/stats.log

# --- Unix command socket (enable and set canonical path) ---
# Some packaged builds default to /var/run/suricata-command.socket (suricatasc manpage).
# We'll make it explicit and configurable.
suricata_unix_socket_enabled: true
suricata_unix_socket_path: /var/run/suricata-command.socket

default_interface: enp1s0



zeek_pkg: "zeek-lts"    # or "zeek" / "zeek-7.0"
zeek_conf_path: /opt/zeek/etc/zeekctl.cfg
zeek_networks_cfg_path: /opt/zeek/etc/networks.cfg
zeek_svc: zeek
# Zeek repository (OBS) for Ubuntu 24.04
zeek_obs_repo_url: "https://download.opensuse.org/repositories/security:/zeek/xUbuntu_24.04/"
zeek_obs_repo_file: "security:zeek"    # /etc/apt/sources.list.d/security:zeek.list
zeek_obs_key_url: "https://download.opensuse.org/repositories/security:/zeek/xUbuntu_24.04/Release.key"



ossec_pkg: wazuh-agent
ossec_conf_path: /var/ossec/etc/ossec.conf
wazuh_key_path: /usr/share/keyrings/wazuh.gpg
wazuh_repo_line: "deb [signed-by={{ wazuh_key_path }}] https://packages.wazuh.com/4.x/apt/ stable main"
ossec_svc: wazuh-agent




prometheus_pkg: prometheus
node_exporter_pkg: prometheus-node-exporter
prometheus_config_path: /etc/prometheus/prometheus.yml
prometheus_svc: prometheus
node_exporter_svc: prometheus-node-exporter


grafana_pkg: grafana # Choose which package to install: grafana (OSS) or grafana-enterprise
grafana_ini_path: /etc/grafana/grafana.ini
grafana_keyring_path: /etc/apt/keyrings/grafana.gpg
grafana_repo_line: "deb [signed-by={{ grafana_keyring_path }}] https://apt.grafana.com stable main"
grafana_svc: grafana-server

rsyslog_pkg: rsyslog
rsyslog_conf_path: /etc/rsyslog.conf





# rsyslog forwarding target (defaults to central server var)
rsyslog_forward_ip: "{{ central_log_server_ip }}"
rsyslog_forward_port_tcp: "{{ central_log_server_port_tcp }}"
rsyslog_forward_port_udp: "{{ central_log_server_port_udp }}"
rsyslog_forward_protocol: "tcp"  # tcp or udp
rsyslog_svc: rsyslog



ufw_pkg: ufw
ufw_svc: ufw





# Non-default repos






# Service names















