---
galaxy_info:
  role_name: packages_patching
  description: APT signature enforcement and cleanup
  author: "Tim Davies"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [24.04]
