- name: Create Cloudflare Access App for Sonarr
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Sonarr"
      domain: "sonarr.{{ cloudflare_zone }}"
      type: "self_hosted"
      session_duration: "24h"
      policies:
        - decision: allow
          include:
            - email:
                email: "{{ access_email }}"
    status_code: 200
  register: sonarr_access_response

- name: Log Sonarr Access App creation
  debug:
    var: sonarr_access_response.json

- name: Create Cloudflare Access App for Radarr
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Radarr"
      domain: "radarr.{{ cloudflare_zone }}"
      type: "self_hosted"
      session_duration: "24h"
      policies:
        - decision: allow
          include:
            - email:
                email: "{{ access_email }}"
    status_code: 200
  register: radarr_access_response

- name: Log Radarr Access App creation
  debug:
    var: radarr_access_response.json
