# 0. Preconditions
- name: Fail if Cloudflare account ID or API token is missing
  fail:
    msg: "cloudflare_account_id or cloudflare_apps_api_token is not set — cannot manage Access apps"
  when:
    - cloudflare_account_id is not defined or cloudflare_account_id | length == 0
    - cloudflare_apps_api_token is not defined or cloudflare_apps_api_token | length == 0

# 1. Get existing Access apps
- name: Get existing Cloudflare Access apps
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: 200
  register: existing_access_apps

# 2. Create missing Access apps
- name: Create Cloudflare Access apps if not already present
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ item.name }}"
      domain: "{{ item.domain }}"
      type: "self_hosted"
      session_duration: "24h"
      policies:
        - decision: allow
          include:
            - email:
                email: "{{ item.email }}"
    status_code: [200, 201]
  loop: "{{ cloudflare_access_apps }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - existing_access_apps.json.success | default(false)
    - item.domain not in (existing_access_apps.json.result | map(attribute='domain') | list | default([]))
  register: created_access_apps

# 3. Log newly created apps
- name: Log newly created apps
  debug:
    var: created_access_apps
  when: created_access_apps is defined

