---
# roles/cloudflared/tasks/create_email_otp_policies.yml

# 0. Preconditions
- name: Fail if created_apps is missing
  fail:
    msg: "created_apps variable is not defined — run create_access_apps.yml first"
  when: created_apps is not defined

# 1. Get existing policies for each app
- name: Get existing policies for each app
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.app_id }}/policies"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    return_content: yes
  register: existing_policies
  loop: "{{ created_apps }}"
  loop_control:
    label: "{{ item.name }}"

# 2. Normalise policy lists
- name: Normalise policy lists
  set_fact:
    normalised_policies: "{{ existing_policies.results | map(attribute='json.result') | map('default', []) | map('list') | list }}"

# 3. Combine apps and policies
- name: Build apps_with_policies list
  set_fact:
    apps_with_policies: "{{ apps_with_policies | default([]) + [ {
        'name': item.0.name,
        'app_id': item.0.app_id,
        'policies': item.1 | default([])
      } ] }}"
  loop: "{{ created_apps | zip(normalised_policies) | list }}"
  loop_control:
    label: "{{ item.0.name }}"

# 4. Delete existing 'Email OTP Policy' if present
- name: Delete existing 'Email OTP Policy' if present
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.0.app_id }}/policies/{{ item.1.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    status_code: 200,204
  loop: "{{ query('subelements', apps_with_policies, 'policies', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.name }}"
  when:
    - item.1 is mapping
    - "'name' in item.1"
    - item.1.name == "Email OTP Policy"

# 5. DEBUG: Show JSON body for each new policy
- name: Show JSON body for Email OTP policy
  debug:
    msg: "{{ {
      'name': 'Email OTP Policy',
      'decision': 'allow',
      'include': [ { 'email': { 'email': [ item.email ] } } ],
      'require': [ { 'login_method': 'onetimepin' } ],
      'precedence': 1
    } | to_nice_json }}"
  loop: "{{ created_apps }}"
  loop_control:
    label: "{{ item.name }}"

# 6. Create new Email OTP policy for each app
- name: Create Email OTP policy for each app
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.app_id }}/policies"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Email OTP Policy"
      decision: allow
      include:
        - email:
            email:
              - "{{ item.email }}"
      require:
        - login_method: "onetimepin"
      precedence: 1
    status_code: [200, 201]
  loop: "{{ created_apps }}"
  loop_control:
    label: "{{ item.name }}"
