# roles/cloudflared/tasks/create_access_apps.yml

# 0. Preconditions
- name: Fail if Cloudflare account ID or API token is missing
  fail:
    msg: "cloudflare_account_id or cloudflare_apps_api_token is not set — cannot manage Access apps"
  when:
    - cloudflare_account_id is not defined or cloudflare_account_id | length == 0
    - cloudflare_apps_api_token is not defined or cloudflare_apps_api_token | length == 0

# 1. Fetch all Access apps
- name: Get list of Access apps
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: 200
  register: access_apps_resp

- name: Fail if API call to get Access apps failed
  fail:
    msg: "Failed to retrieve Access apps: {{ access_apps_resp.json.errors }}"
  when: not access_apps_resp.json.success | default(false)

- name: Set access_apps_list fact
  set_fact:
    access_apps_list: "{{ access_apps_resp.json.result | default([]) }}"

# 2. Create or update each app (launcher‑visible, no per‑app policy)
- name: Create or update Cloudflare Access apps
  uri:
    url: >-
      https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps{{ '/' + existing_app.id if (existing_app is mapping and 'id' in existing_app) else '' }}
    method: "{{ 'PUT' if (existing_app is mapping and 'id' in existing_app) else 'POST' }}"
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ item.name }}"
      domain: "{{ item.domain }}"
      type: "self_hosted"
      session_duration: "1h"
      app_launcher_visible: true
    status_code: [200, 201]
    return_content: yes
  loop: "{{ cloudflare_access_apps }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    existing_app: >-
      {{ access_apps_list
         | selectattr('domain', 'equalto', item.domain)
         | first
         | default({}, true) }}
  register: app_create_results

# 3. Show results
- name: Show created/updated apps
  debug:
    var: app_create_results

# 4. Get App Launcher application
- name: Get App Launcher application
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps?type=app_launcher"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    return_content: yes
    status_code: 200
  register: launcher_resp

- name: Fail if no App Launcher found
  fail:
    msg: "No App Launcher application found in this account."
  when: (launcher_resp.json.result | length) == 0

- name: Set launcher_app fact
  set_fact:
    launcher_app: "{{ launcher_resp.json.result[0] }}"

# 5. Get policies for App Launcher
- name: Get App Launcher policies
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ launcher_app.id }}/policies"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    return_content: yes
    status_code: 200
  register: launcher_policies_resp

- name: Set launcher_policies fact
  set_fact:
    launcher_policies: "{{ launcher_policies_resp.json.result | default([]) }}"

# 6. Ensure timmos.com.au email_domain rule exists
- name: Add timmos.com.au allow policy if missing
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ launcher_app.id }}/policies"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Email Domain Allow Policy"
      decision: "allow"
      include:
        - email_domain:
            domain: "timmos.com.au"
      precedence: >-
        {{
          ((launcher_policies | map(attribute='precedence') | list) | default([0]))
          | max
          + 1
        }}
    status_code: [200, 201]
  when: >
    (launcher_policies | selectattr('include', 'defined') | selectattr('include', 'string') | select('search', 'timmos.com.au') | list | length) == 0
