---
# roles/cloudflared/tasks/enforce_email_domain_policy_timmos.yml

- name: Fail if created_apps is missing
  fail:
    msg: "created_apps variable is not defined — run create_access_apps.yml first"
  when: created_apps is not defined

# 1. Get existing policies for each app
- name: Get existing policies for each app
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.app_id }}/policies"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    return_content: yes
  register: existing_policies
  loop: "{{ created_apps }}"
  loop_control:
    label: "{{ item.name }}"

# 2. Normalise policy lists
- name: Normalise policy lists
  set_fact:
    normalised_policies: "{{ existing_policies.results
                             | map(attribute='json.result')
                             | map('default', [])
                             | map('list')
                             | list }}"

# 3. Combine apps and their policies
- name: Build apps_with_policies list
  set_fact:
    apps_with_policies: "{{ apps_with_policies | default([]) + [ {
        'name': item.0.name,
        'app_id': item.0.app_id,
        'policies': item.1 | default([])
      } ] }}"
  loop: "{{ created_apps | zip(normalised_policies) | list }}"
  loop_control:
    label: "{{ item.0.name }}"

# 4. Delete non‑matching Email OTP Policy
- name: Delete incorrect Email OTP Policy
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.0.app_id }}/policies/{{ item.1.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
    status_code: 200,204
  loop: >-
    {{
      query('subelements', apps_with_policies, 'policies', {'skip_missing': True})
      | selectattr('1.name', 'equalto', 'Email OTP Policy')
      | selectattr('1.include', 'ne', [ { 'email_domain': { 'domains': ['timmos.com.au'] } } ])
      | list
    }}
  loop_control:
    label: "{{ item.0.name }}"

# 5. Create Email OTP Policy if missing or deleted
- name: Create Email OTP Policy for timmos.com.au
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ item.app_id }}/policies"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Email OTP Policy"
      decision: "allow"
      include:
        - email_domain:
            domains:
              - "timmos.com.au"
      require:
        - login_method: "onetimepin"
      precedence: 1
    status_code: [200, 201]
  loop: "{{ apps_with_policies }}"
  loop_control:
    label: "{{ item.name }}"
  when: >
    (
      item.policies | selectattr('name', 'equalto', 'Email OTP Policy') | list | length == 0
    )
    or
    (
      item.policies | selectattr('name', 'equalto', 'Email OTP Policy')
      | selectattr('include', 'ne', [ { 'email_domain': { 'domains': ['timmos.com.au'] } } ])
      | list | length > 0
    )
