# roles/cloudflared/tasks/create_dns_records.yml

- name: Get Zone ID for base domain
  uri:
    url: "https://api.cloudflare.com/client/v4/zones?name={{ cloudflare_zone }}"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: 200
  register: zone_lookup

- name: Set zone_id fact
  set_fact:
    cloudflare_zone_id: "{{ zone_lookup.json.result[0].id }}"

- name: Create proxied CNAME record for each Access app
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone_id }}/dns_records"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "CNAME"
      name: "{{ item.domain }}"
      content: "{{ tunnel_id_final  }}.cfargotunnel.com"
      proxied: true
      ttl: 1
    status_code: 200
    return_content: yes
  loop: "{{ access_apps_list }}"
  when: item.domain is defined and item.domain | length > 0
  register: dns_create_results

- name: Show DNS creation results
  debug:
    var: dns_create_results.results
