- name: Ensure Terraform directory exists
  file:
    path: "{{ cf_terraform_path }}"
    state: directory
    mode: '0755'

- name: Copy CSR generator script
  copy:
    src: origin_csr.sh
    dest: "{{ cf_terraform_path }}/origin_csr.sh"
    mode: '0755'

- name: Run CSR generator
  command: ./origin_csr.sh
  args:
    chdir: "{{ cf_terraform_path }}"
