---
- name: Install cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: "{{ cloudflared_bin_path }}"
    mode: '0755'

- name: Configure cloudflared
  include_tasks: configure_tunnel.yml
  #when: "'ssh' in stig_enabled_tags and not system_is_container | default(false)"

- name: Start Cloudflared tunnel (headless token mode)
  ansible.builtin.command: >
    "{{ cloudflared_bin_path }}" tunnel --config "{{ cloudflared_config_path }}" run "{{ tunnel_id_final }}"
  changed_when: false
  when:
    - tunnel_id_final is defined
    - tunnel_id_final | length > 0


- name: Create Cloudflare Access apps
  include_tasks: create_access_apps.yml
  #when: "'ssh' in stig_enabled_tags and not system_is_container | default(false)"

