---
#- name: Install cloudflared
#  ansible.builtin.get_url:
#    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
#    dest: "{{ cloudflared_bin_path }}"
#    mode: '0755'

#- name: Create Cloudflare Access apps
#  include_tasks: create_access_apps.yml

#- name: Configure cloudflared
#  include_tasks: configure_tunnel.yml
  
#- name: Create or update DNS records for each app
#  include_tasks: create_dns_records.yml

- name: Test Email OTP policy creation for a single app
  vars:
    test_app_id: "f12448c6-02d7-496a-8e1d-27cec4592424"   # Replace with the app_id you want to test
    test_email: "readarr@timmos.com.au"                   # Replace with the email for that app
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/apps/{{ test_app_id }}/policies"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "Email OTP Policy (Test)"
      decision: allow
      include:
        - email_domain:
            domain:
              - "{{ item.email.split('@')[1] }}"
        - email:
            email:
              - "{{ test_email }}"
      require:
        - login_method: "onetimepin"
      precedence: 1
    return_content: yes
    status_code: [200, 201, 400]
  register: policy_test_result

- name: Show full API response for policy test
  debug:
    var: policy_test_result.json
