---
- name: Install cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: "{{ cloudflared_bin_path }}"
    mode: '0755'

- name: Configure cloudflared
  include_tasks: configure_tunnel.yml

- name: Create Cloudflare Access apps
  include_tasks: create_access_apps.yml

- name: Create or update policy for each app
  include_tasks: create_access_policy.yml
  loop: "{{ app_email_map | dict2items }}"
  loop_control:
    loop_var: app_item
  vars:
    app_id: "{{ app_item.key }}"
    app_email: "{{ app_item.value }}"
  when: app_item.value is defined and app_item.value | length > 0
