- name: Clean Terraform directory
  file:
    path: "{{ terraform_dir }}"
    state: absent

- name: Recreate Terraform directory
  file:
    path: "{{ terraform_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Push Terraform configuration to remote
  copy:
    src: terraform/
    dest: "{{ terraform_dir }}/"
    owner: root
    group: root
    mode: '0644'

# --- NEW: Check if tunnel exists via Cloudflare API ---
- name: Check if tunnel exists
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/cfd_tunnel?name={{ tunnel_name }}"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: tunnel_check

- name: Set fact for existing tunnel ID
  set_fact:
    existing_tunnel_id: "{{ (tunnel_check.json.result | first).id if (tunnel_check.json.result | length) > 0 else '' }}"

# --- Terraform init ---
- name: Run Terraform init
  command: terraform init
  args:
    chdir: "{{ terraform_dir }}"
  environment:
    TF_VAR_cloudflare_api_token: "{{ cloudflare_api_token }}"
    TF_VAR_cloudflare_account_id: "{{ cloudflare_account_id }}"
    TF_VAR_tunnel_name: "{{ tunnel_name }}"

# --- Import if exists ---
- name: Check if tunnel is already in Terraform state
  command: terraform state list
  args:
    chdir: "{{ terraform_dir }}"
  register: tf_state_list

- name: Import existing tunnel into Terraform
  command: terraform import cloudflare_zero_trust_tunnel_cloudflared.tunnel {{ existing_tunnel_id }}
  args:
    chdir: "{{ terraform_dir }}"
  when:
    - existing_tunnel_id != ""
    - "'cloudflare_zero_trust_tunnel_cloudflared.tunnel' not in tf_state_list.stdout"

# --- Apply ---
- name: Run Terraform apply
  command: terraform apply -auto-approve
  args:
    chdir: "{{ terraform_dir }}"
  environment:
    TF_VAR_cloudflare_api_token: "{{ cloudflare_api_token }}"
    TF_VAR_cloudflare_account_id: "{{ cloudflare_account_id }}"
    TF_VAR_tunnel_name: "{{ tunnel_name }}"

# --- Outputs ---
- name: Get tunnel ID from Terraform
  command: terraform output -raw tunnel_id
  args:
    chdir: "{{ terraform_dir }}"
  register: tunnel_id_result

- name: Get tunnel credentials JSON from Terraform
  command: terraform output -raw tunnel_credentials_json
  args:
    chdir: "{{ terraform_dir }}"
  register: tunnel_creds_result

# --- Deploy config ---
- name: Ensure /etc/cloudflared exists
  file:
    path: /etc/cloudflared
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Write tunnel credentials file
  copy:
    content: "{{ tunnel_creds_result.stdout }}"
    dest: "/etc/cloudflared/{{ tunnel_id_result.stdout }}.json"
    owner: root
    group: root
    mode: '0600'

- name: Write config.yml for cloudflared
  template:
    src: config.yml.j2
    dest: /etc/cloudflared/config.yml
    owner: root
    group: root
    mode: '0644'

# --- systemd ---
- name: Create systemd service for cloudflared tunnel
  copy:
    dest: /etc/systemd/system/cloudflared.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Cloudflare Tunnel
      After=network.target

      [Service]
      TimeoutStartSec=0
      Type=notify
      ExecStart={{ cloudflared_bin_path }} tunnel --config /etc/cloudflared/config.yml run {{ tunnel_id_result.stdout }}
      Restart=on-failure
      RestartSec=5s
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start cloudflared service
  systemd:
    name: cloudflared
    enabled: yes
    state: started


- name: Include Cloudflare Access app creation
  include_tasks: create_access_apps.yml