---
- name: Install cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: "{{ cloudflared_bin_path }}"
    mode: '0755'

- name: Create Cloudflare Access apps
  include_tasks: create_access_apps.yml

#- name: Assign Cloudflare Access apps' policy
#  include_tasks: create_access_policy.yml

- name: Configure cloudflared
  include_tasks: configure_tunnel.yml
  
- name: Create or update DNS records for each app
  include_tasks: create_dns_records.yml
