- name: Download cloudflared
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: /usr/local/bin/cloudflared
    mode: '0755'

- name: Create cloudflared config directory
  file:
    path: /etc/cloudflared
    state: directory
    mode: '0755'

- name: Upload tunnel config
  template:
    src: config.yml.j2
    dest: /etc/cloudflared/config.yml
    mode: '0644'

- name: Register tunnel as systemd service
  copy:
    dest: /etc/systemd/system/cloudflared.service
    content: |
      [Unit]
      Description=Cloudflare Tunnel
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/cloudflared tunnel --config /etc/cloudflared/config.yml run
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target

- name: Enable and start cloudflared
  systemd:
    name: cloudflared
    enabled: yes
    state: started

- name: Ensure cloudflared is installed
  become: true
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: "{{ cloudflared_bin_path }}"
    mode: '0755'

- name: Create tunnel config directory
  become: true
  file:
    path: /etc/cloudflared
    state: directory
    mode: '0755'

- name: Write tunnel credentials
  become: true
  copy:
    dest: /etc/cloudflared/{{ cloudflare_tunnel_id }}.json
    content: "{{ cloudflare_tunnel_secret }}"
    mode: '0600'

- name: Create config.yml for cloudflared
  become: true
  copy:
    dest: /etc/cloudflared/config.yml
    content: |
      tunnel: {{ cloudflare_tunnel_id }}
      credentials-file: /etc/cloudflared/{{ cloudflare_tunnel_id }}.json
      ingress:
        - hostname: sonarr.timmos.com.au
          service: http://192.168.1.100:8989
        - hostname: radarr.timmos.com.au
          service: http://192.168.1.100:7878
        - service: http_status:404
    mode: '0644'

- name: Start cloudflared tunnel
  become: true
  command: "{{ cloudflared_bin_path }} tunnel run {{ cloudflare_tunnel_name }}"
