- name: Read CSR content
  slurp:
    src: "{{ cf_csr_file }}"
  register: csr_raw

- name: Log current attachment status
  debug:
    msg: "System is currently attached to: {{ cf_global_api_key | default('UNATTACHED') }}"

- name: Request Cloudflare Origin Certificate
  uri:
    url: "https://api.cloudflare.com/client/v4/certificates"
    method: POST
    headers:
      X-Auth-Key: "{{ cf_global_api_key }}"
      X-Auth-Email: "{{ cf_email }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "origin-rsa"
      hostnames: "{{ cf_hostnames }}"
      requested_validity: "{{ cf_cert_validity_days }}"
      csr: "{{ csr_raw.content | b64decode | regex_replace('\n', '\\n') }}"
    return_content: true
  register: cert_response
  no_log: false

- name: Write cert.pem
  become: true
  copy:
    content: "{{ cert_response.json.result.certificate }}"
    dest: "{{ cf_cert_file }}"
    owner: root
    group: root
    mode: '0600'
