- name: Terraform Init
  command: terraform init
  args:
    chdir: "{{ cf_terraform_path }}"

- name: Show rendered hostnames
  debug:
    msg: "{{ cf_hostnames | to_json }}"

- name: Terraform Apply
  environment:
    TF_VAR_cloudflare_email: "{{ cf_email }}"
    TF_VAR_cloudflare_global_api_key: "{{ cloudflare_global_api_token }}"
    TF_VAR_cloudflare_hostnames: "{{ cf_hostnames | to_json }}"
    TF_VAR_cert_validity_days: "{{ cf_cert_validity_days }}"
    TF_VAR_cloudflare_account_id: "{{ cloudflare_account_id }}"
  command: terraform apply -auto-approve
  args:
    chdir: "{{ cf_terraform_path }}"
