---
# roles/cloudflared/tasks/verify_email_domain.yml

- name: Ensure email domain exists (create if missing)
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/email/domains"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      domain: "{{ email_domain_to_verify }}"
    return_content: yes
    status_code: [200, 201]
  register: domain_create_resp

- name: Set verification details
  set_fact:
    cf_email_domain_id: "{{ domain_create_resp.json.result.id }}"
    cf_verification_name: "{{ domain_create_resp.json.result.verification_name }}"
    cf_verification_value: "{{ domain_create_resp.json.result.verification_value }}"
    cf_email_domain_status: "{{ domain_create_resp.json.result.status }}"

- name: Show DNS TXT record if not verified
  debug:
    msg: "Add TXT record for {{ email_domain_to_verify }}: Name='{{ cf_verification_name }}', Value='{{ cf_verification_value }}'"
  when: cf_email_domain_status != "verified"

- pause:
    prompt: "Press Enter once TXT record is added and propagated"
  when: cf_email_domain_status != "verified"

- name: Verify the email domain (only if not already verified)
  uri:
    url: "https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id }}/access/email/domains/{{ cf_email_domain_id }}/verify"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_apps_api_token }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: [200, 201]
  register: verify_resp
  until: verify_resp.json.result.status is defined and verify_resp.json.result.status == "verified"
  retries: 10
  delay: 30
  when: cf_email_domain_status != "verified"

- name: Set final domain status
  set_fact:
    cf_email_domain_final_status: >-
      {{ 'verified' if cf_email_domain_status == 'verified'
         else verify_resp.json.result.status }}
